"use client";
import Link from "next/link";
import { useState } from "react";
import { SiteNav } from "../../components/SiteNav";
import { LANGUAGES, LEVELS, getCategories, type CategoryId, type LanguageId, type Level } from "../../lib/curriculum";
import { loadLearning } from "../../lib/learning";
import { PRACTICE_METHODS, type PracticeMode } from "../../lib/practice";

export default function PracticeIndex(){
 const initial=loadLearning().preferences,[language,setLanguage]=useState<LanguageId>(initial.language),[level,setLevel]=useState<Level>(initial.level),[category,setCategory]=useState<CategoryId>(initial.category);
 function changeLevel(value:Level){setLevel(value);setCategory(getCategories(value)[0].id)}
 const query=`lang=${language}&level=${level}&category=${category}`;
 return <main className="practice-dark min-h-screen bg-[#0B0F17] text-white"><SiteNav/><section className="mx-auto max-w-7xl px-5 py-10 md:px-8 md:py-14">
  <header className="mb-8 flex flex-col gap-5 border-b border-white/[0.08] pb-8 md:flex-row md:items-end md:justify-between"><div><span className="font-mono text-[10px] uppercase tracking-[0.2em] text-neutral-500">RecallFlow / Pratik sistemi</span><h1 className="mt-3 text-3xl font-medium tracking-[-0.04em] text-white md:text-4xl">Çalışma yöntemini seç.</h1><p className="mt-3 max-w-xl text-sm leading-relaxed text-neutral-400">Her yöntem ayrı ve dikkat dağıtmayan bir çalışma odasında açılır. Filtrelerini belirle, tek bir protokole gir ve oturumu tamamla.</p></div><div className="flex items-center gap-3 text-xs text-neutral-500"><span className="h-2 w-2 rounded-full bg-emerald-400 shadow-[0_0_14px_rgba(52,211,153,0.55)]"/><span>7 yöntem kullanıma hazır</span></div></header>
  <section className="mb-8 grid grid-cols-1 overflow-hidden rounded-xl border border-white/[0.08] bg-[#111622] md:grid-cols-3" aria-label="Çalışma filtresi"><Filter label="Dil" value={language} onChange={value=>setLanguage(value as LanguageId)} options={LANGUAGES.map(item=>({value:item.id,label:item.label}))}/><Filter label="Seviye" value={level} onChange={value=>changeLevel(value as Level)} options={LEVELS.map(item=>({value:item,label:item}))}/><Filter label="Kategori" value={category} onChange={value=>setCategory(value as CategoryId)} options={getCategories(level).map(item=>({value:item.id,label:item.label}))}/></section>
  <section className="grid grid-cols-1 gap-4 md:grid-cols-3" aria-label="Öğrenme yöntemleri">{PRACTICE_METHODS.map(method=><Link key={method.id} href={`/practice/${method.id}?${query}`} className="group relative flex min-h-56 flex-col overflow-hidden rounded-xl border border-white/[0.08] bg-[#111622] p-5 transition-all duration-300 hover:-translate-y-0.5 hover:border-white/20 hover:bg-[#161D2E] hover:shadow-[0_18px_45px_rgba(0,0,0,0.28)] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-violet-400"><div className="pointer-events-none absolute inset-x-0 top-0 h-24 bg-gradient-to-b from-white/[0.03] to-transparent"/><header className="relative flex items-start justify-between"><span className="grid h-9 w-9 place-items-center rounded-lg border border-white/[0.08] bg-white/[0.03] text-neutral-300 transition-colors duration-300 group-hover:border-white/15 group-hover:text-white"><MethodIcon mode={method.id}/></span><span className="rounded border border-white/[0.05] bg-white/[0.04] px-2 py-0.5 font-mono text-[10px] tracking-wider text-neutral-400">{method.meta}</span></header><div className="relative mt-10 flex-1"><h2 className="text-base font-medium tracking-tight text-white">{method.title}</h2><p className="mt-2 text-sm leading-relaxed text-neutral-400">{method.description}</p></div><footer className="relative mt-8 flex items-center justify-between border-t border-white/[0.06] pt-4"><span className="font-mono text-[10px] uppercase tracking-wider text-neutral-500">{method.duration}</span><span className="flex items-center gap-2 text-xs font-medium text-neutral-300 transition-colors group-hover:text-white">Odayı aç <Arrow/></span></footer></Link>)}</section>
 </section></main>
}

function Filter({label,value,onChange,options}:{label:string;value:string;onChange:(value:string)=>void;options:{value:string;label:string}[]}){return <label className="flex min-h-16 flex-col justify-center border-b border-white/[0.08] px-4 last:border-0 md:border-b-0 md:border-r"><span className="mb-1 font-mono text-[9px] uppercase tracking-[0.16em] text-neutral-500">{label}</span><select className="w-full appearance-none bg-transparent text-sm font-medium text-neutral-200 outline-none" value={value} onChange={event=>onChange(event.target.value)}>{options.map(option=><option className="bg-[#111622]" key={option.value} value={option.value}>{option.label}</option>)}</select></label>}
function Arrow(){return <svg className="h-3.5 w-3.5 transition-transform duration-300 group-hover:translate-x-1" viewBox="0 0 16 16" fill="none" aria-hidden="true"><path d="M3 8h9M8.5 4.5 12 8l-3.5 3.5" stroke="currentColor" strokeWidth="1.25" strokeLinecap="round" strokeLinejoin="round"/></svg>}
function MethodIcon({mode}:{mode:PracticeMode}){const paths:Record<PracticeMode,React.ReactNode>={flash:<><rect x="4" y="3" width="12" height="14" rx="2"/><path d="m8 8 2-2 2 2M10 6v6"/></>,choice:<><path d="M5 6h10M5 10h10M5 14h6"/><circle cx="2.5" cy="6" r=".75" fill="currentColor" stroke="none"/><circle cx="2.5" cy="10" r=".75" fill="currentColor" stroke="none"/><circle cx="2.5" cy="14" r=".75" fill="currentColor" stroke="none"/></>,free:<><path d="M4 15h12M6 12.5 13.5 5 16 7.5 8.5 15H6z"/></>,listen:<><path d="M4 9a6 6 0 0 1 12 0v4a2 2 0 0 1-2 2h-2V9h4M4 9v6H2a2 2 0 0 1-2-2V9h4"/></>,sentence:<><path d="M3 5h14M3 9h11M3 13h8"/></>,category:<><rect x="2" y="2" width="6" height="6" rx="1"/><rect x="12" y="2" width="6" height="6" rx="1"/><rect x="7" y="12" width="6" height="6" rx="1"/><path d="M5 8v2h10V8M10 10v2"/></>,text:<><path d="M4 2h9l3 3v13H4zM13 2v4h4M7 10h6M7 13h6"/></>};return <svg className="h-4 w-4" viewBox="0 0 20 20" fill="none" stroke="currentColor" strokeWidth="1.25" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{paths[mode]}</svg>}
