"use client";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { SiteNav } from "../../components/SiteNav";
import { DeckControls } from "../../components/DeckControls";
import { SpeakButton } from "../../components/SpeakButton";
import { buildDeck, normalizeAnswer, type CategoryId, type LanguageId, type Level } from "../../lib/curriculum";
import { loadLearning, recordReview, savePreferences, type Rating } from "../../lib/learning";
type Mode="cards"|"listen"|"write";
export default function LearnPage(){
 const initial=loadLearning().preferences;const[language,setLanguage]=useState<LanguageId>(initial.language);const[level,setLevel]=useState<Level>(initial.level);const[category,setCategory]=useState<CategoryId>(initial.category);const[mode,setMode]=useState<Mode>("cards");const[index,setIndex]=useState(0);const[session,setSession]=useState(0);const[open,setOpen]=useState(false);const[answer,setAnswer]=useState("");const[state,setState]=useState<"idle"|"correct"|"wrong">("idle");const deck=useMemo(()=>buildDeck(language,level,category),[language,level,category]);const learning=loadLearning(),dueDeck=deck.filter(item=>!learning.reviews[item.id]||learning.reviews[item.id].dueAt<=Date.now()),activeDeck=dueDeck.length?dueDeck:deck;const card=activeDeck[index%activeDeck.length];
 const choices=useMemo(()=>[card,...[11,29,47].map(n=>deck[(card.index+n)%deck.length])].sort((a,b)=>a.id.localeCompare(b.id)),[card,deck]);
 useEffect(()=>{const params=new URLSearchParams(location.search);const lang=params.get("lang") as LanguageId|null,lev=params.get("level") as Level|null,cat=params.get("category") as CategoryId|null,pos=Number(params.get("index"));if(lang)setLanguage(lang);if(lev)setLevel(lev);if(cat)setCategory(cat);if(Number.isFinite(pos))setIndex(pos)},[]);
 useEffect(()=>{savePreferences({language,level,category});setOpen(false);setAnswer("");setState("idle")},[language,level,category]);
 useEffect(()=>{function keys(event:KeyboardEvent){if(mode!=="cards"||event.target instanceof HTMLInputElement)return;if(event.code==="Space"){event.preventDefault();setOpen(x=>!x)}if(open&&["1","2","3"].includes(event.key))next(({"1":"again","2":"hard","3":"good"}as const)[event.key as "1"|"2"|"3"])}window.addEventListener("keydown",keys);return()=>window.removeEventListener("keydown",keys)},[open,mode,card.id]);
 function reset(){setOpen(false);setAnswer("");setState("idle")}
 function next(rating:Rating){recordReview(card.id,rating);setSession(x=>x+1);setIndex(0);reset()}
 function skip(){setIndex(x=>x+1);reset()}
 function check(e:FormEvent){e.preventDefault();const correct=normalizeAnswer(answer)===normalizeAnswer(card.term);setState(correct?"correct":"wrong");setOpen(true)}
 function choose(value:string){const correct=value===card.id;setState(correct?"correct":"wrong");setOpen(true);if(correct)recordReview(card.id,"good")}
 return <main><SiteNav/><header className="page-head compact"><span className="eyebrow">01 / ÇALIŞMA STÜDYOSU</span><h1>Tek kart.<br/><em>Tam odak.</em></h1><p>Karar yorgunluğu yok. Son seçimlerin hazır; modunu seç ve on kartlık oturumu bitir.</p></header><section className="learn-shell"><DeckControls language={language} level={level} category={category} onLanguage={setLanguage} onLevel={setLevel} onCategory={setCategory}/><div className="mode-switch" role="tablist">{[["cards","KELİME KARTI"],["listen","DİNLE & BUL"],["write","YAZARAK HATIRLA"]].map(([id,label],i)=><button role="tab" aria-selected={mode===id} key={id} className={mode===id?"active":""} onClick={()=>{setMode(id as Mode);reset()}}><b>0{i+1}</b>{label}</button>)}</div><div className="learn-stage"><aside><span>OTURUM · {dueDeck.length} HAZIR</span><b>{String(session%10+1).padStart(2,"0")}<i>/10</i></b><div><i style={{width:`${(session%10+1)*10}%`}}/></div><p>Boşluk: kartı çevir · 1: tekrar · 2: zor · 3: bildim</p><button onClick={skip}>BU KARTI ATLA →</button></aside><article className={`focus-card ${state}`} aria-live="polite"><header><span>{card.level} · {card.categoryLabel}</span><span>#{String(card.index+1).padStart(3,"0")}</span></header>{mode==="cards"&&<><button className="flip-area" onClick={()=>setOpen(!open)}><small>{open?"ANLAMI":"HEDEF DİL"}</small><strong>{open?card.turkish:card.term}</strong><p>{open?card.example:"Düşün, sonra kartı çevir · BOŞLUK"}</p></button><div className={`rate ${open?"visible":"locked"}`} aria-hidden={!open}><button disabled={!open} onClick={()=>next("again")}>TEKRAR <small>1 dk · 1</small></button><button disabled={!open} onClick={()=>next("hard")}>ZOR <small>10 dk · 2</small></button><button disabled={!open} onClick={()=>next("good")}>BİLDİM <small>1+ gün · 3</small></button></div></>}{mode==="listen"&&<div className="listen-mode"><SpeakButton card={card} label="▶"/><h2>Dinle. Seç.</h2><div className="choice-grid">{choices.map(choice=><button disabled={open} key={choice.id} className={open&&choice.id===card.id?"right":""} onClick={()=>choose(choice.id)}>{choice.turkish}</button>)}</div>{open&&<button className="answer-toggle" onClick={()=>next(state==="correct"?"good":"again")}>{state==="correct"?"DOĞRU · SONRAKİ →":`${card.term} · TEKRARLA →`}</button>}</div>}{mode==="write"&&<form className="write-mode" onSubmit={check}><small>TÜRKÇEDEN HEDEF DİLE</small><h2>{card.turkish}</h2><input aria-label="Hedef dilde cevap" value={answer} onChange={e=>{setAnswer(e.target.value);setState("idle");setOpen(false)}} placeholder="Karşılığını yaz…"/><p>{state==="correct"?`Doğru · ${card.example}`:state==="wrong"?`Doğru cevap: ${card.term} · ${card.example}`:"Aksan işaretleri otomatik normalize edilir."}</p><button>KONTROL ET ↗</button>{open&&<button type="button" onClick={()=>next(state==="correct"?"good":"again")}>SONRAKİ →</button>}</form>}</article></div></section></main>}
