import type {
  Category,
  Lang,
  LanguageMeta,
  Level,
  Reading,
} from "@/types/domain";

export const languages: Record<Lang, LanguageMeta> = {
  en: {
    name: "İngilizce",
    native: "English",
    flag: "EN",
    voice: "en-US",
    color: "#c7ff4a",
  },
  de: {
    name: "Almanca",
    native: "Deutsch",
    flag: "DE",
    voice: "de-DE",
    color: "#ff795c",
  },
  fr: {
    name: "Fransızca",
    native: "Français",
    flag: "FR",
    voice: "fr-FR",
    color: "#8ca8ff",
  },
};
export const categoryLabels: Record<Category, string> = {
  daily: "Günlük yaşam",
  people: "İnsanlar",
  food: "Yiyecek",
  travel: "Seyahat",
  nature: "Doğa",
  home: "Ev & Eşyalar",
  work: "İş & Eğitim",
  feelings: "Duygular",
};

type Gender = "m" | "f" | "n";
export interface Concept {
  tr: string;
  en: string;
  de: string;
  deGender: Gender;
  fr: string;
  frGender: Exclude<Gender, "n">;
  category: Category;
}
export const concepts: readonly Concept[] = [
  {
    tr: "ev",
    en: "house",
    de: "Haus",
    deGender: "n",
    fr: "maison",
    frGender: "f",
    category: "home",
  },
  {
    tr: "aile",
    en: "family",
    de: "Familie",
    deGender: "f",
    fr: "famille",
    frGender: "f",
    category: "people",
  },
  {
    tr: "arkadaş",
    en: "friend",
    de: "Freund",
    deGender: "m",
    fr: "ami",
    frGender: "m",
    category: "people",
  },
  {
    tr: "çocuk",
    en: "child",
    de: "Kind",
    deGender: "n",
    fr: "enfant",
    frGender: "m",
    category: "people",
  },
  {
    tr: "öğretmen",
    en: "teacher",
    de: "Lehrer",
    deGender: "m",
    fr: "professeur",
    frGender: "m",
    category: "work",
  },
  {
    tr: "kitap",
    en: "book",
    de: "Buch",
    deGender: "n",
    fr: "livre",
    frGender: "m",
    category: "work",
  },
  {
    tr: "okul",
    en: "school",
    de: "Schule",
    deGender: "f",
    fr: "école",
    frGender: "f",
    category: "work",
  },
  {
    tr: "iş",
    en: "work",
    de: "Arbeit",
    deGender: "f",
    fr: "travail",
    frGender: "m",
    category: "work",
  },
  {
    tr: "masa",
    en: "table",
    de: "Tisch",
    deGender: "m",
    fr: "table",
    frGender: "f",
    category: "home",
  },
  {
    tr: "sandalye",
    en: "chair",
    de: "Stuhl",
    deGender: "m",
    fr: "chaise",
    frGender: "f",
    category: "home",
  },
  {
    tr: "kapı",
    en: "door",
    de: "Tür",
    deGender: "f",
    fr: "porte",
    frGender: "f",
    category: "home",
  },
  {
    tr: "pencere",
    en: "window",
    de: "Fenster",
    deGender: "n",
    fr: "fenêtre",
    frGender: "f",
    category: "home",
  },
  {
    tr: "su",
    en: "water",
    de: "Wasser",
    deGender: "n",
    fr: "eau",
    frGender: "f",
    category: "food",
  },
  {
    tr: "ekmek",
    en: "bread",
    de: "Brot",
    deGender: "n",
    fr: "pain",
    frGender: "m",
    category: "food",
  },
  {
    tr: "kahve",
    en: "coffee",
    de: "Kaffee",
    deGender: "m",
    fr: "café",
    frGender: "m",
    category: "food",
  },
  {
    tr: "elma",
    en: "apple",
    de: "Apfel",
    deGender: "m",
    fr: "pomme",
    frGender: "f",
    category: "food",
  },
  {
    tr: "yemek",
    en: "meal",
    de: "Essen",
    deGender: "n",
    fr: "repas",
    frGender: "m",
    category: "food",
  },
  {
    tr: "şehir",
    en: "city",
    de: "Stadt",
    deGender: "f",
    fr: "ville",
    frGender: "f",
    category: "travel",
  },
  {
    tr: "tren",
    en: "train",
    de: "Zug",
    deGender: "m",
    fr: "train",
    frGender: "m",
    category: "travel",
  },
  {
    tr: "uçak",
    en: "plane",
    de: "Flugzeug",
    deGender: "n",
    fr: "avion",
    frGender: "m",
    category: "travel",
  },
  {
    tr: "otel",
    en: "hotel",
    de: "Hotel",
    deGender: "n",
    fr: "hôtel",
    frGender: "m",
    category: "travel",
  },
  {
    tr: "bilet",
    en: "ticket",
    de: "Fahrkarte",
    deGender: "f",
    fr: "billet",
    frGender: "m",
    category: "travel",
  },
  {
    tr: "yol",
    en: "road",
    de: "Straße",
    deGender: "f",
    fr: "route",
    frGender: "f",
    category: "travel",
  },
  {
    tr: "deniz",
    en: "sea",
    de: "Meer",
    deGender: "n",
    fr: "mer",
    frGender: "f",
    category: "nature",
  },
  {
    tr: "dağ",
    en: "mountain",
    de: "Berg",
    deGender: "m",
    fr: "montagne",
    frGender: "f",
    category: "nature",
  },
  {
    tr: "orman",
    en: "forest",
    de: "Wald",
    deGender: "m",
    fr: "forêt",
    frGender: "f",
    category: "nature",
  },
  {
    tr: "güneş",
    en: "sun",
    de: "Sonne",
    deGender: "f",
    fr: "soleil",
    frGender: "m",
    category: "nature",
  },
  {
    tr: "yağmur",
    en: "rain",
    de: "Regen",
    deGender: "m",
    fr: "pluie",
    frGender: "f",
    category: "nature",
  },
  {
    tr: "mutluluk",
    en: "happiness",
    de: "Glück",
    deGender: "n",
    fr: "bonheur",
    frGender: "m",
    category: "feelings",
  },
  {
    tr: "umut",
    en: "hope",
    de: "Hoffnung",
    deGender: "f",
    fr: "espoir",
    frGender: "m",
    category: "feelings",
  },
  {
    tr: "korku",
    en: "fear",
    de: "Angst",
    deGender: "f",
    fr: "peur",
    frGender: "f",
    category: "feelings",
  },
  {
    tr: "merak",
    en: "curiosity",
    de: "Neugier",
    deGender: "f",
    fr: "curiosité",
    frGender: "f",
    category: "feelings",
  },
  {
    tr: "zaman",
    en: "time",
    de: "Zeit",
    deGender: "f",
    fr: "temps",
    frGender: "m",
    category: "daily",
  },
  {
    tr: "sabah",
    en: "morning",
    de: "Morgen",
    deGender: "m",
    fr: "matin",
    frGender: "m",
    category: "daily",
  },
  {
    tr: "gece",
    en: "night",
    de: "Nacht",
    deGender: "f",
    fr: "nuit",
    frGender: "f",
    category: "daily",
  },
  {
    tr: "telefon",
    en: "phone",
    de: "Telefon",
    deGender: "n",
    fr: "téléphone",
    frGender: "m",
    category: "home",
  },
  {
    tr: "bilgisayar",
    en: "computer",
    de: "Computer",
    deGender: "m",
    fr: "ordinateur",
    frGender: "m",
    category: "work",
  },
  {
    tr: "para",
    en: "money",
    de: "Geld",
    deGender: "n",
    fr: "argent",
    frGender: "m",
    category: "daily",
  },
  {
    tr: "müzik",
    en: "music",
    de: "Musik",
    deGender: "f",
    fr: "musique",
    frGender: "f",
    category: "daily",
  },
  {
    tr: "film",
    en: "film",
    de: "Film",
    deGender: "m",
    fr: "film",
    frGender: "m",
    category: "daily",
  },
];

export const levelExampleIndex: Record<Level, number> = {
  A1: 0,
  A2: 1,
  B1: 2,
  B2: 3,
  C1: 4,
};
export const readings: Record<
  Lang,
  Record<Level, Reading>
> = Object.fromEntries(
  (["en", "de", "fr"] as Lang[]).map((lang) => [
    lang,
    Object.fromEntries(
      (["A1", "A2", "B1", "B2", "C1"] as Level[]).map((level, index) => [
        level,
        {
          title:
            lang === "en"
              ? [
                  "A quiet morning",
                  "A weekend plan",
                  "The city that learns",
                  "Learning beyond the classroom",
                  "Language and identity",
                ][index]
              : lang === "de"
                ? [
                    "Ein ruhiger Morgen",
                    "Ein Plan fürs Wochenende",
                    "Die lernende Stadt",
                    "Lernen außerhalb des Klassenzimmers",
                    "Sprache und Identität",
                  ][index]
                : [
                    "Un matin calme",
                    "Un projet pour le week-end",
                    "La ville qui apprend",
                    "Apprendre hors de la classe",
                    "Langue et identité",
                  ][index],
          text:
            lang === "en"
              ? [
                  "Mia wakes up early. She opens the window, drinks water and writes three words in her notebook.",
                  "This weekend, Mia is going to visit a nearby town. She has already bought her ticket and planned the route.",
                  "Every corner of a city can become a classroom. A menu teaches useful phrases and a station trains the ear.",
                  "Independent learners deliberately create situations in which new vocabulary becomes necessary rather than merely familiar.",
                  "A language does more than transmit information; it also carries memories, social expectations and ways of interpreting experience.",
                ][index]
              : lang === "de"
                ? [
                    "Mia steht früh auf. Sie öffnet das Fenster, trinkt Wasser und schreibt drei Wörter in ihr Heft.",
                    "Am Wochenende will Mia eine nahe Stadt besuchen. Sie hat schon ihre Fahrkarte gekauft und den Weg geplant.",
                    "Jede Ecke einer Stadt kann zum Klassenzimmer werden. Eine Speisekarte lehrt nützliche Sätze und ein Bahnhof trainiert das Ohr.",
                    "Selbstständige Lernende schaffen bewusst Situationen, in denen neuer Wortschatz notwendig und nicht nur vertraut wird.",
                    "Eine Sprache vermittelt nicht nur Informationen; sie trägt auch Erinnerungen, soziale Erwartungen und Arten, Erfahrungen zu deuten.",
                  ][index]
                : [
                    "Mia se lève tôt. Elle ouvre la fenêtre, boit de l’eau et écrit trois mots dans son cahier.",
                    "Ce week-end, Mia va visiter une ville proche. Elle a déjà acheté son billet et préparé son trajet.",
                    "Chaque coin d’une ville peut devenir une salle de classe. Un menu enseigne des phrases utiles et une gare entraîne l’oreille.",
                    "Les apprenants autonomes créent délibérément des situations où le nouveau vocabulaire devient nécessaire plutôt que simplement familier.",
                    "Une langue ne transmet pas seulement des informations ; elle porte aussi des souvenirs, des attentes sociales et des manières d’interpréter l’expérience.",
                  ][index],
          duration: `0${index + 1}:${20 + index * 7}`,
        },
      ]),
    ),
  ]),
) as Record<Lang, Record<Level, Reading>>;
