export type VocabularyWord = {
  id: string; de: string; tr: string; article?: string; example: string;
  translation: string; category: string; lesson: number;
};

type CategorySource = { title: string; color: string; terms: string };

const sources: CategorySource[] = [
  { title: "Selamlaşma & Tanışma", color: "#ff5b45", terms: `Hallo|merhaba;Guten Morgen|günaydın;Guten Tag|iyi günler;Guten Abend|iyi akşamlar;Gute Nacht|iyi geceler;Tschüss|hoşça kal;Auf Wiedersehen|görüşmek üzere;Bis bald|yakında görüşürüz;Bis morgen|yarın görüşürüz;Willkommen|hoş geldiniz;Danke|teşekkürler;Vielen Dank|çok teşekkürler;Bitte|lütfen / rica ederim;Entschuldigung|affedersiniz;Es tut mir leid|üzgünüm;Wie geht es dir?|nasılsın?;Mir geht es gut|iyiyim;Und dir?|ya sen?;der Name|isim;der Vorname|ad;der Nachname|soyadı;heißen|adı olmak;sich vorstellen|kendini tanıtmak;kennenlernen|tanışmak;kommen aus|bir yerden gelmek;wohnen|ikamet etmek;leben|yaşamak;sprechen|konuşmak;Deutsch|Almanca;Türkisch|Türkçe;die Sprache|dil;das Land|ülke;die Stadt|şehir;die Adresse|adres;die Telefonnummer|telefon numarası;die E-Mail-Adresse|e-posta adresi;Wie heißt du?|adın ne?;Woher kommst du?|nerelisin?;Wo wohnst du?|nerede oturuyorsun?;Freut mich|memnun oldum` },
  { title: "Aile & İnsanlar", color: "#f18eb8", terms: `die Familie|aile;die Eltern|ebeveynler;die Mutter|anne;der Vater|baba;die Schwester|kız kardeş;der Bruder|erkek kardeş;die Tochter|kız evlat;der Sohn|erkek evlat;die Großmutter|büyükanne;der Großvater|büyükbaba;die Oma|nine;der Opa|dede;die Tante|teyze / hala;der Onkel|amca / dayı;die Cousine|kız kuzen;der Cousin|erkek kuzen;die Ehefrau|eş / karı;der Ehemann|eş / koca;die Freundin|kız arkadaş;der Freund|erkek arkadaş;das Kind|çocuk;das Baby|bebek;der Mensch|insan;die Person|kişi;der Mann|adam;die Frau|kadın;das Mädchen|kız çocuk;der Junge|erkek çocuk;verheiratet|evli;ledig|bekâr;geschieden|boşanmış;jung|genç;alt|yaşlı;nett|nazik;freundlich|arkadaş canlısı;zusammen|birlikte;besuchen|ziyaret etmek;helfen|yardım etmek;lieben|sevmek;verwandt|akraba` },
  { title: "Ev & Günlük Yaşam", color: "#ffc93d", terms: `das Haus|ev;die Wohnung|daire;das Zimmer|oda;das Wohnzimmer|oturma odası;das Schlafzimmer|yatak odası;die Küche|mutfak;das Badezimmer|banyo;der Balkon|balkon;der Garten|bahçe;die Tür|kapı;das Fenster|pencere;die Wand|duvar;der Boden|zemin;der Tisch|masa;der Stuhl|sandalye;das Bett|yatak;der Schrank|dolap;das Sofa|kanepe;die Lampe|lamba;der Kühlschrank|buzdolabı;der Herd|ocak;die Waschmaschine|çamaşır makinesi;der Schlüssel|anahtar;die Miete|kira;der Nachbar|erkek komşu;die Nachbarin|kadın komşu;aufstehen|kalkmak;duschen|duş almak;anziehen|giyinmek;frühstücken|kahvaltı yapmak;aufräumen|toparlamak;putzen|temizlemek;kochen|yemek pişirmek;waschen|yıkamak;schlafen|uyumak;zu Hause|evde;oben|yukarıda;unten|aşağıda;drinnen|içeride;draußen|dışarıda` },
  { title: "Yiyecek & İçecek", color: "#41d8c0", terms: `das Essen|yemek;das Getränk|içecek;das Frühstück|kahvaltı;das Mittagessen|öğle yemeği;das Abendessen|akşam yemeği;das Brot|ekmek;das Brötchen|küçük ekmek;die Butter|tereyağı;der Käse|peynir;das Ei|yumurta;die Milch|süt;der Kaffee|kahve;der Tee|çay;das Wasser|su;der Saft|meyve suyu;das Fleisch|et;der Fisch|balık;das Hähnchen|tavuk;der Reis|pirinç;die Kartoffel|patates;die Nudel|makarna;das Gemüse|sebze;das Obst|meyve;der Apfel|elma;die Banane|muz;die Orange|portakal;die Tomate|domates;die Gurke|salatalık;der Salat|salata;die Suppe|çorba;der Kuchen|pasta;der Zucker|şeker;das Salz|tuz;hungrig|aç;durstig|susamış;essen|yemek;içmek|trinken;bestellen|sipariş vermek;schmecken|tadı olmak;Guten Appetit|afiyet olsun` },
  { title: "Şehir & Ulaşım", color: "#2f66f3", terms: `die Stadt|şehir;das Dorf|köy;die Straße|sokak;der Platz|meydan;die Kreuzung|kavşak;die Ampel|trafik ışığı;der Bahnhof|tren istasyonu;die Haltestelle|durak;der Flughafen|havaalanı;der Bus|otobüs;die Straßenbahn|tramvay;die U-Bahn|metro;der Zug|tren;das Taxi|taksi;das Fahrrad|bisiklet;das Auto|araba;das Ticket|bilet;die Fahrkarte|ulaşım bileti;der Fahrplan|sefer tarifesi;die Abfahrt|kalkış;die Ankunft|varış;die Richtung|yön;der Weg|yol;die Brücke|köprü;der Park|park;die Bank|banka;die Post|postane;die Polizei|polis;das Rathaus|belediye binası;fahren|araçla gitmek;gehen|yürümek;einsteigen|binmek;aussteigen|inmek;umsteigen|aktarma yapmak;abbiegen|dönmek;geradeaus|dümdüz;links|sol;rechts|sağ;nah|yakın;weit|uzak` },
  { title: "Okul & Öğrenme", color: "#a98af0", terms: `die Schule|okul;der Kurs|kurs;die Klasse|sınıf;der Lehrer|erkek öğretmen;die Lehrerin|kadın öğretmen;der Schüler|erkek öğrenci;die Schülerin|kız öğrenci;das Buch|kitap;das Heft|defter;der Stift|kalem;der Bleistift|kurşun kalem;der Kugelschreiber|tükenmez kalem;das Papier|kâğıt;die Seite|sayfa;die Aufgabe|görev;die Übung|alıştırma;die Prüfung|sınav;die Antwort|cevap;die Frage|soru;das Wort|kelime;der Satz|cümle;die Grammatik|dil bilgisi;der Text|metin;die Pause|mola;lernen|öğrenmek;lesen|okumak;schreiben|yazmak;hören|dinlemek;wiederholen|tekrar etmek;verstehen|anlamak;erklären|açıklamak;fragen|sormak;antworten|cevaplamak;üben|alıştırma yapmak;buchstabieren|harf harf söylemek;richtig|doğru;falsch|yanlış;leicht|kolay;schwer|zor;fertig|bitmiş / hazır` },
  { title: "İş & Meslekler", color: "#ff8d5c", terms: `die Arbeit|iş;der Beruf|meslek;die Firma|şirket;das Büro|ofis;der Chef|erkek yönetici;die Chefin|kadın yönetici;der Kollege|erkek iş arkadaşı;die Kollegin|kadın iş arkadaşı;der Arzt|erkek doktor;die Ärztin|kadın doktor;der Verkäufer|erkek satış görevlisi;die Verkäuferin|kadın satış görevlisi;der Fahrer|erkek sürücü;die Fahrerin|kadın sürücü;der Koch|erkek aşçı;die Köchin|kadın aşçı;der Kellner|erkek garson;die Kellnerin|kadın garson;der Ingenieur|erkek mühendis;die Ingenieurin|kadın mühendis;der Mechaniker|erkek tamirci;die Sekretärin|sekreter;der Termin|randevu;die Besprechung|toplantı;die Bewerbung|iş başvurusu;die Pause|mola;das Gehalt|maaş;arbeiten|çalışmak;verdienen|kazanmak;beginnen|başlamak;enden|bitmek;anrufen|telefon etmek;schicken|göndermek;drucken|yazdırmak;unterschreiben|imzalamak;suchen|aramak;finden|bulmak;beschäftigt|meşgul;arbeitslos|işsiz;Vollzeit|tam zamanlı` },
  { title: "Zaman & Tarih", color: "#57b9ed", terms: `die Zeit|zaman;die Uhr|saat;die Stunde|saatlik süre;die Minute|dakika;der Tag|gün;die Woche|hafta;der Monat|ay;das Jahr|yıl;der Montag|pazartesi;der Dienstag|salı;der Mittwoch|çarşamba;der Donnerstag|perşembe;der Freitag|cuma;der Samstag|cumartesi;der Sonntag|pazar;der Januar|ocak;der Februar|şubat;der März|mart;der April|nisan;der Mai|mayıs;der Juni|haziran;der Juli|temmuz;der August|ağustos;der September|eylül;der Oktober|ekim;der November|kasım;der Dezember|aralık;heute|bugün;gestern|dün;morgen|yarın;jetzt|şimdi;später|daha sonra;früh|erken;spät|geç;morgens|sabahları;mittags|öğle vakti;abends|akşamları;nachts|geceleri;halb|buçuk;Viertel|çeyrek` },
  { title: "Hava & Mevsimler", color: "#67cc84", terms: `das Wetter|hava;die Sonne|güneş;der Regen|yağmur;der Schnee|kar;der Wind|rüzgâr;die Wolke|bulut;der Himmel|gökyüzü;die Temperatur|sıcaklık;der Grad|derece;der Frühling|ilkbahar;der Sommer|yaz;der Herbst|sonbahar;der Winter|kış;sonnig|güneşli;regnerisch|yağmurlu;windig|rüzgârlı;bewölkt|bulutlu;neblig|sisli;kalt|soğuk;warm|ılık / sıcak;heiß|çok sıcak;kühl|serin;trocken|kuru;nass|ıslak;frieren|üşümek;regnen|yağmur yağmak;schneien|kar yağmak;scheinen|parlamak;die Wettervorhersage|hava tahmini;der Regenschirm|şemsiye;die Jacke|ceket;das Gewitter|fırtına;der Sturm|kuvvetli fırtına;das Eis|buz;draußen|dışarıda;drinnen|içeride;über null|sıfırın üzerinde;unter null|sıfırın altında;Wie ist das Wetter?|hava nasıl?;Es wird kalt|hava soğuyacak` },
  { title: "Sağlık & Vücut", color: "#ff6e8c", terms: `der Körper|vücut;der Kopf|baş;das Gesicht|yüz;das Auge|göz;das Ohr|kulak;die Nase|burun;der Mund|ağız;der Zahn|diş;der Hals|boğaz;der Arm|kol;die Hand|el;der Finger|parmak;der Bauch|karın;der Rücken|sırt;das Bein|bacak;der Fuß|ayak;das Herz|kalp;die Gesundheit|sağlık;die Krankheit|hastalık;der Schmerz|ağrı;das Fieber|ateş;der Husten|öksürük;die Erkältung|soğuk algınlığı;die Apotheke|eczane;das Krankenhaus|hastane;der Arzttermin|doktor randevusu;krank|hasta;gesund|sağlıklı;müde|yorgun;fit|formda;wehtun|ağrımak;husten|öksürmek;atmen|nefes almak;untersuchen|muayene etmek;die Tablette|tablet ilaç;die Medizin|ilaç;Gute Besserung|geçmiş olsun;Was fehlt Ihnen?|neyiniz var?;Ich habe Schmerzen|ağrım var;Hilfe!|yardım!` },
  { title: "Alışveriş & Para", color: "#f2b234", terms: `das Geschäft|mağaza;der Laden|dükkân;der Supermarkt|süpermarket;der Markt|pazar;die Bäckerei|fırın;die Kasse|kasa;der Preis|fiyat;das Geld|para;der Euro|avro;der Cent|sent;die Rechnung|hesap / fatura;der Kassenbon|fiş;die Kreditkarte|kredi kartı;das Bargeld|nakit;das Angebot|indirimli teklif;die Größe|beden;die Farbe|renk;der Kunde|erkek müşteri;die Kundin|kadın müşteri;kaufen|satın almak;verkaufen|satmak;bezahlen|ödemek;kosten|fiyatı olmak;brauchen|ihtiyacı olmak;nehmen|almak;probieren|denemek;passen|uymak;umtauschen|değiştirmek;billig|ucuz;teuer|pahalı;günstig|uygun fiyatlı;offen|açık;geschlossen|kapalı;bar|nakit olarak;Wie viel kostet das?|bu ne kadar?;Ich nehme das|bunu alıyorum;Haben Sie …?|… var mı?;Kann ich mit Karte zahlen?|kartla ödeyebilir miyim?;zu groß|fazla büyük;zu klein|fazla küçük` },
  { title: "Boş Zaman & Hobiler", color: "#8c8df4", terms: `die Freizeit|boş zaman;das Hobby|hobi;der Sport|spor;die Musik|müzik;der Film|film;das Kino|sinema;das Theater|tiyatro;das Museum|müze;das Konzert|konser;das Spiel|oyun;das Buch|kitap;die Zeitung|gazete;der Computer|bilgisayar;das Internet|internet;das Foto|fotoğraf;der Verein|kulüp;Fußball spielen|futbol oynamak;schwimmen|yüzmek;laufen|koşmak;tanzen|dans etmek;singen|şarkı söylemek;malen|resim yapmak;fotografieren|fotoğraf çekmek;reisen|seyahat etmek;wandern|doğa yürüyüşü yapmak;kochen|yemek yapmak;lesen|okumak;fernsehen|televizyon izlemek;Musik hören|müzik dinlemek;Freunde treffen|arkadaşlarla buluşmak;Spaß machen|eğlenceli olmak;interessant|ilginç;langweilig|sıkıcı;frei|boş / müsait;am Wochenende|hafta sonunda;jeden Tag|her gün;manchmal|bazen;oft|sık sık;selten|nadiren;nie|asla` },
  { title: "Seyahat & Tatil", color: "#35b8b0", terms: `die Reise|seyahat;der Urlaub|tatil;das Hotel|otel;das Zimmer|oda;die Rezeption|resepsiyon;die Reservierung|rezervasyon;der Pass|pasaport;der Koffer|bavul;die Tasche|çanta;die Karte|harita / kart;der Flughafen|havaalanı;das Flugzeug|uçak;der Flug|uçuş;der Bahnsteig|peron;das Gleis|hat;die Fahrkarte|bilet;die Jugendherberge|gençlik yurdu;der Campingplatz|kamp alanı;der Strand|plaj;das Meer|deniz;der Berg|dağ;die Sehenswürdigkeit|turistik yer;buchen|rezervasyon yapmak;reservieren|ayırtmak;abfahren|hareket etmek;ankommen|varmak;abfliegen|havalanmak;übernachten|gecelemek;packen|bavul hazırlamak;mitnehmen|yanına almak;zeigen|göstermek;besichtigen|gezmek / ziyaret etmek;ein Einzelzimmer|tek kişilik oda;ein Doppelzimmer|çift kişilik oda;mit Frühstück|kahvaltı dâhil;ohne Frühstück|kahvaltısız;Hin und zurück|gidiş dönüş;nur Hinfahrt|tek yön;Gute Reise|iyi yolculuklar;Wo ist Gleis drei?|üçüncü peron nerede?` },
  { title: "Giysiler & Renkler", color: "#df78b5", terms: `die Kleidung|giysi;das Hemd|gömlek;die Bluse|bluz;das T-Shirt|tişört;der Pullover|kazak;die Jacke|ceket;der Mantel|palto;die Hose|pantolon;der Rock|etek;das Kleid|elbise;der Schuh|ayakkabı;der Stiefel|bot;die Socke|çorap;die Mütze|bere;der Hut|şapka;der Schal|atkı;die Brille|gözlük;die Tasche|çanta;die Größe|beden;die Umkleidekabine|deneme kabini;rot|kırmızı;blau|mavi;grün|yeşil;gelb|sarı;schwarz|siyah;weiß|beyaz;grau|gri;braun|kahverengi;rosa|pembe;orange|turuncu;hell|açık renk;dunkel|koyu renk;tragen|giymek;anziehen|giymek;ausziehen|çıkarmak;anprobieren|denemek;passen|uymak;stehen|yakışmak;zu eng|fazla dar;zu weit|fazla bol` },
  { title: "Temel Fiiller", color: "#f06b4f", terms: `sein|olmak;haben|sahip olmak;werden|olmak / dönüşmek;können|yapabilmek;müssen|zorunda olmak;wollen|istemek;sollen|gerekmek;dürfen|izinli olmak;mögen|sevmek / hoşlanmak;möchten|istemek;yapmak|machen;tun|yapmak;gehen|gitmek;kommen|gelmek;fahren|araçla gitmek;bleiben|kalmak;wohnen|oturmak / ikamet etmek;leben|yaşamak;arbeiten|çalışmak;lernen|öğrenmek;sprechen|konuşmak;sagen|söylemek;fragen|sormak;antworten|cevaplamak;sehen|görmek;hören|duymak;lesen|okumak;schreiben|yazmak;essen|yemek;trinken|içmek;kaufen|satın almak;bezahlen|ödemek;geben|vermek;nehmen|almak;bringen|getirmek;holen|gidip getirmek;finden|bulmak;suchen|aramak;brauchen|ihtiyacı olmak;helfen|yardım etmek` },
  { title: "Sıfatlar & Zarflar", color: "#5c8df6", terms: `gut|iyi;schlecht|kötü;groß|büyük;klein|küçük;lang|uzun;kurz|kısa;neu|yeni;alt|eski / yaşlı;jung|genç;schön|güzel;hässlich|çirkin;leicht|kolay / hafif;schwer|zor / ağır;schnell|hızlı;langsam|yavaş;laut|yüksek sesli;leise|sessiz;warm|ılık;kalt|soğuk;heiß|sıcak;teuer|pahalı;billig|ucuz;voll|dolu;leer|boş;offen|açık;geschlossen|kapalı;richtig|doğru;falsch|yanlış;wichtig|önemli;interessant|ilginç;müde|yorgun;hungrig|aç;sicher|güvenli / emin;gefährlich|tehlikeli;sehr|çok;auch|de / ayrıca;nur|sadece;schon|çoktan;noch|hâlâ / daha;wieder|tekrar` },
  { title: "Edatlar & Bağlaçlar", color: "#9d81d8", terms: `in|içinde;an|yanında / üzerinde;auf|üstünde;unter|altında;über|üzerinde;vor|önünde;hinter|arkasında;neben|yanında;zwischen|arasında;mit|ile;ohne|olmadan;für|için;gegen|karşı;durch|içinden;um|etrafında / saat;aus|-den / -dan;bei|yanında;nach|-e doğru / sonra;von|-den / -dan;zu|-e / -a;seit|-den beri;bis|-e kadar;ab|-den itibaren;und|ve;oder|veya;aber|ama;denn|çünkü;sondern|aksine;weil|çünkü;dass|-diğini;wenn|eğer / olduğunda;deshalb|bu nedenle;trotzdem|buna rağmen;zuerst|önce;dann|sonra;danach|ondan sonra;später|daha sonra;links von|solunda;rechts von|sağında;gegenüber|karşısında` },
  { title: "Goethe A1 Çekirdek", color: "#ef5f62", terms: `das Formular|form;der Familienname|soyadı;das Geburtsdatum|doğum tarihi;der Geburtsort|doğum yeri;die Staatsangehörigkeit|uyruk;der Wohnort|ikamet yeri;die Unterschrift|imza;die Anmeldung|kayıt;die Einladung|davet;die Nachricht|mesaj;die Anzeige|ilan;die Öffnungszeit|çalışma saati;der Eingang|giriş;der Ausgang|çıkış;die Information|bilgi;der Treffpunkt|buluşma noktası;die Verspätung|gecikme;die Durchsage|anons;der Notfall|acil durum;die Hilfe|yardım;ausfüllen|doldurmak;ankreuzen|işaretlemek;unterschreiben|imzalamak;vereinbaren|kararlaştırmak;absagen|iptal etmek;verschieben|ertelemek;teilnehmen|katılmak;mitbringen|yanında getirmek;warten|beklemek;bitten|rica etmek;Wie bitte?|efendim?;Können Sie das wiederholen?|tekrar edebilir misiniz?;Sprechen Sie bitte langsam|lütfen yavaş konuşun;Ich verstehe nicht|anlamıyorum;Was bedeutet das?|bu ne demek?;Wie schreibt man das?|bu nasıl yazılır?;Darf ich fragen?|sorabilir miyim?;Ich hätte gern …|… istiyorum;Können Sie mir helfen?|bana yardım edebilir misiniz?;Vielen Dank für Ihre Hilfe|yardımınız için çok teşekkürler` },
];

const clean = (raw: string) => {
  const match = raw.match(/^(der|die|das)\s+(.+)$/);
  return match ? { article: match[1], word: match[2] } : { word: raw };
};

function exampleFor(raw: string, tr: string) {
  const { article, word } = clean(raw);
  if (raw.includes("?") || raw.includes("!") || raw.includes("…")) return { de: raw, tr };
  if (article) return { de: `Hier ist ${article} ${word}.`, tr: `Burada ${tr} var.` };
  if (/en$/.test(word) && !word.includes(" ")) return { de: `Ich möchte heute ${word}.`, tr: `Bugün ${tr} istiyorum.` };
  if (word.includes(" ") || /^[A-ZÄÖÜ]/.test(word)) return { de: `Ich sage: „${word}.“`, tr: `Şöyle söylüyorum: “${tr}.“` };
  return { de: `Das ist ${word}.`, tr: `Bu ${tr}.` };
}

export const vocabularyCategories = sources.map((source, categoryIndex) => {
  const words: VocabularyWord[] = source.terms.split(";").map((entry, index) => {
    const [rawValue, trValue] = entry.split("|");
    const [raw, tr] = rawValue === "içmek" ? ["trinken", "içmek"] : rawValue === "yapmak" ? ["machen", "yapmak"] : [rawValue, trValue];
    const { article, word } = clean(raw);
    const example = exampleFor(raw, tr);
    return { id: `${categoryIndex + 1}-${index + 1}`, de: word, tr, article, example: example.de, translation: example.tr, category: source.title, lesson: Math.floor(index / 20) + 1 };
  });
  return { title: source.title, color: source.color, words, lessonCount: Math.ceil(words.length / 20) };
});

export const vocabularyWords = vocabularyCategories.flatMap(category => category.words);
export const vocabularyLessons = vocabularyCategories.flatMap(category =>
  Array.from({ length: category.lessonCount }, (_, index) => ({
    id: `${category.title}-${index + 1}`,
    category: category.title,
    number: index + 1,
    title: index === 0 ? "Temel kelimeler" : "Günlük kullanım",
    words: category.words.filter(word => word.lesson === index + 1),
  })),
);
