export type Lang='en'|'de'|'fr'; export type Level='A1'|'A2'|'B1'|'B2'|'C1';
export const languages={en:{name:'İngilizce',native:'English',flag:'EN',voice:'en-US',color:'#c7ff4a'},de:{name:'Almanca',native:'Deutsch',flag:'DE',voice:'de-DE',color:'#ff795c'},fr:{name:'Fransızca',native:'Français',flag:'FR',voice:'fr-FR',color:'#8ca8ff'}};
export const levels:Level[]=['A1','A2','B1','B2','C1'];
export const categories=['Günlük yaşam','İnsanlar','Yiyecek','Seyahat','Doğa','Ev & Eşyalar','İş & Eğitim','Duygular'];
const concepts=[
['ev','house','Haus','maison','Günlük yaşam'],['aile','family','Familie','famille','İnsanlar'],['arkadaş','friend','Freund','ami','İnsanlar'],['çocuk','child','Kind','enfant','İnsanlar'],['öğretmen','teacher','Lehrer','professeur','İş & Eğitim'],['kitap','book','Buch','livre','İş & Eğitim'],['okul','school','Schule','école','İş & Eğitim'],['iş','work','Arbeit','travail','İş & Eğitim'],['masa','table','Tisch','table','Ev & Eşyalar'],['sandalye','chair','Stuhl','chaise','Ev & Eşyalar'],['kapı','door','Tür','porte','Ev & Eşyalar'],['pencere','window','Fenster','fenêtre','Ev & Eşyalar'],['su','water','Wasser','eau','Yiyecek'],['ekmek','bread','Brot','pain','Yiyecek'],['kahve','coffee','Kaffee','café','Yiyecek'],['elma','apple','Apfel','pomme','Yiyecek'],['yemek','meal','Essen','repas','Yiyecek'],['şehir','city','Stadt','ville','Seyahat'],['tren','train','Zug','train','Seyahat'],['uçak','plane','Flugzeug','avion','Seyahat'],['otel','hotel','Hotel','hôtel','Seyahat'],['bilet','ticket','Fahrkarte','billet','Seyahat'],['yol','road','Straße','route','Seyahat'],['deniz','sea','Meer','mer','Doğa'],['dağ','mountain','Berg','montagne','Doğa'],['orman','forest','Wald','forêt','Doğa'],['güneş','sun','Sonne','soleil','Doğa'],['yağmur','rain','Regen','pluie','Doğa'],['mutluluk','happiness','Glück','bonheur','Duygular'],['umut','hope','Hoffnung','espoir','Duygular'],['korku','fear','Angst','peur','Duygular'],['merak','curiosity','Neugier','curiosité','Duygular'],['zaman','time','Zeit','temps','Günlük yaşam'],['sabah','morning','Morgen','matin','Günlük yaşam'],['gece','night','Nacht','nuit','Günlük yaşam'],['telefon','phone','Telefon','téléphone','Ev & Eşyalar'],['bilgisayar','computer','Computer','ordinateur','İş & Eğitim'],['para','money','Geld','argent','Günlük yaşam'],['müzik','music','Musik','musique','Günlük yaşam'],['film','film','Film','film','Günlük yaşam']
] as const;
const mods={en:['new','old','small','large','beautiful','important','useful','nearby','familiar','interesting','quiet','bright','daily','favorite','different'],de:['neu','alt','klein','groß','schön','wichtig','nützlich','nah','bekannt','interessant','ruhig','hell','täglich','liebste','anders'],fr:['nouveau','ancien','petit','grand','beau','important','utile','proche','familier','intéressant','calme','lumineux','quotidien','préféré','différent'],tr:['yeni','eski','küçük','büyük','güzel','önemli','faydalı','yakındaki','tanıdık','ilginç','sakin','aydınlık','günlük','favori','farklı']};
const example=(lang:Lang,word:string,tr:string,level:Level,i:number)=>{const rows={en:[`This ${word} is part of my day.`,`I often think about the ${word}.`,`We talked about the ${word} yesterday.`],de:[`Dieses ${word} gehört zu meinem Tag.`,`Ich denke oft an ${word}.`,`Wir haben gestern über ${word} gesprochen.`],fr:[`Ce ${word} fait partie de ma journée.`,`Je pense souvent à ${word}.`,`Nous avons parlé de ${word} hier.`]};const trRows=[`Bu ${tr} günümün bir parçası.`,`${tr} hakkında sık sık düşünüyorum.`,`${tr} hakkında dün konuştuk.`]; const k=level==='A1'?0:level==='A2'?1:2;return {target:rows[lang][k],tr:trRows[k]}};
export type Card={id:string;word:string;tr:string;category:string;example:string;exampleTr:string};
export function deck(lang:Lang,level:Level):Card[]{const li=lang==='en'?1:lang==='de'?2:3;return Array.from({length:600},(_,i)=>{const c=concepts[i%concepts.length],m=Math.floor(i/concepts.length)%15;const word=`${mods[lang][m]} ${c[li]}`;const tr=`${mods.tr[m]} ${c[0]}`;const ex=example(lang,word,tr,level,i);return{id:`${lang}-${level}-${i}`,word,tr,category:c[4],example:ex.target,exampleTr:ex.tr}})}
export const readings={en:{A1:['The quiet morning','Mia wakes up early. She opens the window, drinks a glass of water and writes three new words in her notebook. Then she walks to school with her friend.'],B1:['The city that learns','Every corner of a city can become a classroom. A menu teaches useful phrases, a station trains the ear, and a short conversation turns passive knowledge into a living skill.']},de:{A1:['Ein ruhiger Morgen','Mia steht früh auf. Sie öffnet das Fenster, trinkt ein Glas Wasser und schreibt drei neue Wörter in ihr Heft. Dann geht sie mit ihrer Freundin zur Schule.'],B1:['Die lernende Stadt','Jede Ecke einer Stadt kann zum Klassenzimmer werden. Eine Speisekarte lehrt nützliche Sätze, ein Bahnhof trainiert das Ohr und ein kurzes Gespräch macht Wissen lebendig.']},fr:{A1:['Un matin calme','Mia se lève tôt. Elle ouvre la fenêtre, boit un verre d’eau et écrit trois nouveaux mots dans son cahier. Puis elle va à l’école avec son amie.'],B1:['La ville qui apprend','Chaque coin d’une ville peut devenir une salle de classe. Un menu enseigne des phrases utiles, une gare entraîne l’oreille et une courte conversation rend le savoir vivant.']}};
