export const LANGUAGES = [
  { id: "en", code: "EN", label: "İngilizce", locale: "en-US" },
  { id: "de", code: "DE", label: "Almanca", locale: "de-DE" },
  { id: "fr", code: "FR", label: "Fransızca", locale: "fr-FR" },
  { id: "es", code: "ES", label: "İspanyolca", locale: "es-ES" },
  { id: "pt", code: "PT", label: "Portekizce", locale: "pt-PT" },
] as const;

export const LEVELS = ["A1", "A2", "B1", "B2", "C1", "C2"] as const;
export const CATEGORIES = [
  { id: "daily", label: "Günlük Hayat", icon: "◒" }, { id: "people", label: "İnsan & Duygu", icon: "◉" },
  { id: "food", label: "Yemek", icon: "✦" }, { id: "travel", label: "Seyahat", icon: "↗" },
  { id: "work", label: "İş & Eğitim", icon: "▰" }, { id: "nature", label: "Doğa & Kent", icon: "≈" },
] as const;
export type LanguageId = typeof LANGUAGES[number]["id"];
export type Level = typeof LEVELS[number];
export type CategoryId = typeof CATEGORIES[number]["id"];
export type PartOfSpeech = "isim" | "fiil" | "sıfat" | "zarf" | "ifade";
export type ExamSkill = "okuma" | "dinleme" | "yazma" | "konuşma";

export const LEVEL_CATEGORIES: Record<Level, ReadonlyArray<{ id: CategoryId; label: string; icon: string }>> = {
  A1: [{id:"daily",label:"Ev & Günlük Temeller",icon:"◒"},{id:"people",label:"Aile & Tanışma",icon:"◉"},{id:"food",label:"Temel Yiyecekler",icon:"✦"},{id:"travel",label:"Şehirde Yön Bulma",icon:"↗"},{id:"work",label:"Okul & Meslekler",icon:"▰"},{id:"nature",label:"Hava & Mevsimler",icon:"≈"}],
  A2: [{id:"daily",label:"Rutinler & Hizmetler",icon:"◒"},{id:"people",label:"Duygular & Davranış",icon:"◉"},{id:"food",label:"Restoran & Alışveriş",icon:"✦"},{id:"travel",label:"Plan & Konaklama",icon:"↗"},{id:"work",label:"Görevler & Beceriler",icon:"▰"},{id:"nature",label:"Mahalle & Çevre",icon:"≈"}],
  B1: [{id:"daily",label:"Deneyim & Değişim",icon:"◒"},{id:"people",label:"İlişkiler & Görüşler",icon:"◉"},{id:"food",label:"Beslenme & Sağlık",icon:"✦"},{id:"travel",label:"Sorunlar & Çözümler",icon:"↗"},{id:"work",label:"Eğitim & Kariyer",icon:"▰"},{id:"nature",label:"Çevre & Yaşam",icon:"≈"}],
  B2: [{id:"daily",label:"Yaşam Biçimleri",icon:"◒"},{id:"people",label:"Toplum & Etkileşim",icon:"◉"},{id:"food",label:"Tüketim & Yemek Kültürü",icon:"✦"},{id:"travel",label:"Hareketlilik & Kültür",icon:"↗"},{id:"work",label:"Profesyonel İletişim",icon:"▰"},{id:"nature",label:"İklim & Kentleşme",icon:"≈"}],
  C1: [{id:"daily",label:"Kamusal & Özel Alan",icon:"◒"},{id:"people",label:"Kimlik & Psikoloji",icon:"◉"},{id:"food",label:"Gastronomi & Politika",icon:"✦"},{id:"travel",label:"Göç & Aidiyet",icon:"↗"},{id:"work",label:"Akademi & Kurumlar",icon:"▰"},{id:"nature",label:"Ekoloji & Sürdürülebilirlik",icon:"≈"}],
  C2: [{id:"daily",label:"Gündelik Söylem",icon:"◒"},{id:"people",label:"Öznellik & Etik",icon:"◉"},{id:"food",label:"Gıda Etiği & Söylem",icon:"✦"},{id:"travel",label:"Küresel Hareketlilik",icon:"↗"},{id:"work",label:"Bilgi & İktidar",icon:"▰"},{id:"nature",label:"İnsan–Doğa İlişkisi",icon:"≈"}],
};
export function getCategories(level: Level) { return LEVEL_CATEGORIES[level]; }

export const EXAM_PROFILES: Record<LanguageId, Record<Level, string>> = {
  en:{A1:"Cambridge Pre-A1/A1",A2:"A2 Key",B1:"B1 Preliminary",B2:"B2 First",C1:"C1 Advanced",C2:"C2 Proficiency"},
  de:{A1:"Goethe-Zertifikat A1",A2:"Goethe-Zertifikat A2",B1:"Goethe-Zertifikat B1",B2:"Goethe-Zertifikat B2",C1:"Goethe-Zertifikat C1",C2:"Goethe-Zertifikat C2"},
  fr:{A1:"DELF A1",A2:"DELF A2",B1:"DELF B1",B2:"DELF B2",C1:"DALF C1",C2:"DALF C2"},
  es:{A1:"DELE A1",A2:"DELE A2",B1:"DELE B1",B2:"DELE B2",C1:"DELE C1",C2:"DELE C2"},
  pt:{A1:"CAPLE A1 hazırlık",A2:"CIPLE A2",B1:"DEPLE B1",B2:"DIPLE B2",C1:"DAPLE C1",C2:"DUPLE C2"},
};

type Translation = Record<LanguageId, string> & { tr: string };
type Seed = Translation & { pos: PartOfSpeech };
export type WordCard = {
  id:string; language:LanguageId; level:Level; category:CategoryId; categoryLabel:string; index:number;
  term:string; lemma:string; turkish:string; partOfSpeech:PartOfSpeech; exam:string; skill:ExamSkill;
  example:string; exampleTr:string; reviewStatus:"editoryal çekirdek";
};

function parse(block:string): Seed[] {
  return block.trim().split("\n").map(line=>{const [pos,tr,en,de,fr,es,pt]=line.split("|");return {pos:pos as PartOfSpeech,tr,en,de,fr,es,pt};});
}

const bank: Record<Level, Record<CategoryId, Seed[]>> = {
 A1:{
  daily:parse(`isim|anahtar|key|Schlüssel|clé|llave|chave\nisim|pencere|window|Fenster|fenêtre|ventana|janela\nfiil|uyanmak|wake up|aufwachen|se réveiller|despertarse|acordar`),
  people:parse(`isim|soyadı|surname|Nachname|nom de famille|apellido|apelido\nifade|memnun oldum|nice to meet you|freut mich|enchanté|encantado|muito prazer\nisim|ebeveyn|parent|Elternteil|parent|progenitor|progenitor`),
  food:parse(`isim|ekmek|bread|Brot|pain|pan|pão\nisim|kahvaltı|breakfast|Frühstück|petit-déjeuner|desayuno|pequeno-almoço\nsıfat|susamış|thirsty|durstig|assoiffé|sediento|sedento`),
  travel:parse(`isim|bilet|ticket|Fahrkarte|billet|billete|bilhete\nifade|düz devam|straight ahead|geradeaus|tout droit|todo recto|sempre em frente\nisim|durak|stop|Haltestelle|arrêt|parada|paragem`),
  work:parse(`isim|ödev|homework|Hausaufgabe|devoirs|deberes|trabalho de casa\nisim|meslek|job|Beruf|métier|profesión|profissão\nfiil|tekrarlamak|repeat|wiederholen|répéter|repetir|repetir`),
  nature:parse(`isim|yağmur|rain|Regen|pluie|lluvia|chuva\nsıfat|bulutlu|cloudy|bewölkt|nuageux|nublado|nublado\nisim|ilkbahar|spring|Frühling|printemps|primavera|primavera`),
 },
 A2:{
  daily:parse(`isim|randevu|appointment|Termin|rendez-vous|cita|marcação\nfiil|ödünç almak|borrow|ausleihen|emprunter|pedir prestado|pedir emprestado\nisim|tamirat|repair|Reparatur|réparation|reparación|reparação`),
  people:parse(`sıfat|sabırlı|patient|geduldig|patient|paciente|paciente\nfiil|özlemek|miss|vermissen|manquer|echar de menos|sentir falta\nisim|davet|invitation|Einladung|invitation|invitación|convite`),
  food:parse(`isim|hesap|bill|Rechnung|addition|cuenta|conta\nsıfat|baharatlı|spicy|scharf|épicé|picante|picante\nfiil|sipariş vermek|order|bestellen|commander|pedir|pedir`),
  travel:parse(`isim|rezervasyon|reservation|Reservierung|réservation|reserva|reserva\nfiil|gecikmek|be delayed|sich verspäten|être en retard|retrasarse|atrasar-se\nisim|konaklama|accommodation|Unterkunft|hébergement|alojamiento|alojamento`),
  work:parse(`isim|vardiya|shift|Schicht|poste|turno|turno\nfiil|başvurmak|apply|sich bewerben|postuler|solicitar|candidatar-se\nisim|deneyim|experience|Erfahrung|expérience|experiencia|experiência`),
  nature:parse(`isim|geri dönüşüm|recycling|Recycling|recyclage|reciclaje|reciclagem\nisim|gürültü|noise|Lärm|bruit|ruido|ruído\nsıfat|kalabalık|crowded|überfüllt|bondé|abarrotado|lotado`),
 },
 B1:{
  daily:parse(`isim|alışkanlık|habit|Gewohnheit|habitude|hábito|hábito\nfiil|üstesinden gelmek|overcome|überwinden|surmonter|superar|superar\nisim|dönüm noktası|turning point|Wendepunkt|tournant|punto de inflexión|ponto de viragem`),
  people:parse(`isim|uzlaşma|compromise|Kompromiss|compromis|compromiso|compromisso\nfiil|ikna etmek|persuade|überzeugen|persuader|persuadir|persuadir\nsıfat|güvenilir|reliable|zuverlässig|fiable|fiable|fiável`),
  food:parse(`isim|besin|nutrient|Nährstoff|nutriment|nutriente|nutriente\nsıfat|dengeli|balanced|ausgewogen|équilibré|equilibrado|equilibrado\nisim|alerji|allergy|Allergie|allergie|alergia|alergia`),
  travel:parse(`isim|şikâyet|complaint|Beschwerde|réclamation|queja|reclamação\nfiil|iptal etmek|cancel|stornieren|annuler|cancelar|cancelar\nisim|aktarma|connection|Anschluss|correspondance|conexión|ligação`),
  work:parse(`isim|son teslim tarihi|deadline|Abgabetermin|date limite|fecha límite|prazo\nfiil|değerlendirmek|assess|beurteilen|évaluer|evaluar|avaliar\nisim|nitelik|qualification|Qualifikation|qualification|cualificación|qualificação`),
  nature:parse(`isim|kuraklık|drought|Dürre|sécheresse|sequía|seca\nfiil|korumak|preserve|bewahren|préserver|preservar|preservar\nisim|atık|waste|Abfall|déchet|residuo|resíduo`),
 },
 B2:{
  daily:parse(`isim|mahremiyet|privacy|Privatsphäre|vie privée|privacidad|privacidade\nfiil|önceliklendirmek|prioritise|priorisieren|prioriser|priorizar|priorizar\nsıfat|sürdürülebilir|sustainable|nachhaltig|durable|sostenible|sustentável`),
  people:parse(`isim|önyargı|bias|Voreingenommenheit|préjugé|sesgo|preconceito\nfiil|dışlamak|exclude|ausgrenzen|exclure|excluir|excluir\nisim|dayanışma|solidarity|Solidarität|solidarité|solidaridad|solidariedade`),
  food:parse(`isim|tüketim|consumption|Konsum|consommation|consumo|consumo\nisim|tedarik zinciri|supply chain|Lieferkette|chaîne d’approvisionnement|cadena de suministro|cadeia de abastecimento\nsıfat|mevsimlik|seasonal|saisonal|saisonnier|de temporada|sazonal`),
  travel:parse(`isim|kültür şoku|culture shock|Kulturschock|choc culturel|choque cultural|choque cultural\nfiil|uyum sağlamak|adapt|sich anpassen|s’adapter|adaptarse|adaptar-se\nisim|kitle turizmi|mass tourism|Massentourismus|tourisme de masse|turismo de masas|turismo de massas`),
  work:parse(`isim|geri bildirim|feedback|Rückmeldung|retour|retroalimentación|feedback\nfiil|müzakere etmek|negotiate|verhandeln|négocier|negociar|negociar\nisim|iş yükü|workload|Arbeitsbelastung|charge de travail|carga de trabajo|carga de trabalho`),
  nature:parse(`isim|karbon ayak izi|carbon footprint|CO₂-Fußabdruck|empreinte carbone|huella de carbono|pegada de carbono\nfiil|azaltmak|mitigate|mindern|atténuer|mitigar|mitigar\nisim|kentsel yayılma|urban sprawl|Zersiedelung|étalement urbain|expansión urbana|expansão urbana`),
 },
 C1:{
  daily:parse(`isim|yabancılaşma|alienation|Entfremdung|aliénation|alienación|alienação\nisim|görünmez emek|invisible labour|unsichtbare Arbeit|travail invisible|trabajo invisible|trabalho invisível\nfiil|içselleştirmek|internalise|verinnerlichen|intérioriser|interiorizar|interiorizar`),
  people:parse(`isim|aidiyet|belonging|Zugehörigkeit|appartenance|pertenencia|pertença\nisim|öz farkındalık|self-awareness|Selbstwahrnehmung|conscience de soi|autoconciencia|autoconsciência\nsıfat|çelişkili|ambivalent|ambivalent|ambivalent|ambivalente|ambivalente`),
  food:parse(`isim|gıda egemenliği|food sovereignty|Ernährungssouveränität|souveraineté alimentaire|soberanía alimentaria|soberania alimentar\nisim|israf|wastefulness|Verschwendung|gaspillage|despilfarro|desperdício\nsıfat|izlenebilir|traceable|rückverfolgbar|traçable|trazable|rastreável`),
  travel:parse(`isim|yerinden edilme|displacement|Vertreibung|déplacement forcé|desplazamiento|deslocação\nisim|diaspora|diaspora|Diaspora|diaspora|diáspora|diáspora\nfiil|bütünleşmek|integrate|sich integrieren|s’intégrer|integrarse|integrar-se`),
  work:parse(`isim|akran değerlendirmesi|peer review|Begutachtung|évaluation par les pairs|revisión por pares|revisão por pares\nisim|kurumsal yönetişim|governance|Governance|gouvernance|gobernanza|governação\nfiil|gerekçelendirmek|substantiate|begründen|étayer|fundamentar|fundamentar`),
  nature:parse(`isim|biyolojik çeşitlilik|biodiversity|Biodiversität|biodiversité|biodiversidad|biodiversidade\nisim|iklim direnci|climate resilience|Klimaresilienz|résilience climatique|resiliencia climática|resiliência climática\nfiil|yeniden canlandırmak|regenerate|regenerieren|régénérer|regenerar|regenerar`),
 },
 C2:{
  daily:parse(`isim|sıradanlığın politikası|politics of the ordinary|Politik des Alltäglichen|politique de l’ordinaire|política de lo cotidiano|política do quotidiano\nisim|zımni uzlaşım|tacit convention|stillschweigende Konvention|convention tacite|convención tácita|convenção tácita\nfiil|sorunsallaştırmak|problematise|problematisieren|problématiser|problematizar|problematizar`),
  people:parse(`isim|öznelerarasılık|intersubjectivity|Intersubjektivität|intersubjectivité|intersubjetividad|intersubjetividade\nisim|ahlaki fail|moral agent|moralischer Akteur|agent moral|agente moral|agente moral\nsıfat|indirgemeci|reductionist|reduktionistisch|réductionniste|reduccionista|reducionista`),
  food:parse(`isim|metalaşma|commodification|Kommodifizierung|marchandisation|mercantilización|mercantilização\nisim|dağıtım adaleti|distributive justice|Verteilungsgerechtigkeit|justice distributive|justicia distributiva|justiça distributiva\nsıfat|sömürücü|exploitative|ausbeuterisch|prédateur|explotador|exploratório`),
  travel:parse(`isim|ulusötesicilik|transnationalism|Transnationalismus|transnationalisme|transnacionalismo|transnacionalismo\nisim|sınır rejimi|border regime|Grenzregime|régime frontalier|régimen fronterizo|regime fronteiriço\nfiil|yersizyurtsuzlaştırmak|deterritorialise|deterritorialisieren|déterritorialiser|desterritorializar|desterritorializar`),
  work:parse(`isim|bilgi kuramı|epistemology|Erkenntnistheorie|épistémologie|epistemología|epistemologia\nisim|kurumsal atalet|institutional inertia|institutionelle Trägheit|inertie institutionnelle|inercia institucional|inércia institucional\nfiil|çürütmek|refute|widerlegen|réfuter|refutar|refutar`),
  nature:parse(`isim|insanmerkezcilik|anthropocentrism|Anthropozentrismus|anthropocentrisme|antropocentrismo|antropocentrismo\nisim|gezegensel sınır|planetary boundary|planetare Grenze|limite planétaire|límite planetario|limite planetário\nfiil|yeniden yabanlaştırmak|rewild|wiederverwildern|réensauvager|renaturalizar|renaturalizar`),
 }
};

const extra: Record<Level, Record<CategoryId, Seed[]>> = {
 A1:{
  daily:parse(`isim|yatak|bed|Bett|lit|cama|cama\nisim|banyo|bathroom|Badezimmer|salle de bains|baño|casa de banho\nisim|saat|clock|Uhr|horloge|reloj|relógio\nfiil|temizlemek|clean|putzen|nettoyer|limpiar|limpar\nfiil|açmak|open|öffnen|ouvrir|abrir|abrir\nfiil|kapatmak|close|schließen|fermer|cerrar|fechar\nsıfat|hazır|ready|bereit|prêt|listo|pronto`),
  people:parse(`isim|kardeş|sibling|Geschwister|frère ou sœur|hermano|irmão\nisim|arkadaş|friend|Freund|ami|amigo|amigo\nisim|komşu|neighbour|Nachbar|voisin|vecino|vizinho\nsıfat|genç|young|jung|jeune|joven|jovem\nsıfat|nazik|kind|freundlich|gentil|amable|gentil\nfiil|tanışmak|meet|kennenlernen|rencontrer|conocer|conhecer\nfiil|yaşamak|live|wohnen|habiter|vivir|morar`),
  food:parse(`isim|su|water|Wasser|eau|agua|água\nisim|süt|milk|Milch|lait|leche|leite\nisim|elma|apple|Apfel|pomme|manzana|maçã\nisim|peynir|cheese|Käse|fromage|queso|queijo\nfiil|yemek|eat|essen|manger|comer|comer\nfiil|içmek|drink|trinken|boire|beber|beber\nsıfat|aç|hungry|hungrig|affamé|hambriento|com fome`),
  travel:parse(`isim|istasyon|station|Bahnhof|gare|estación|estação\nisim|otobüs|bus|Bus|bus|autobús|autocarro\nisim|harita|map|Karte|carte|mapa|mapa\nisim|sol|left|links|gauche|izquierda|esquerda\nisim|sağ|right|rechts|droite|derecha|direita\nfiil|gitmek|go|gehen|aller|ir|ir\nfiil|gelmek|come|kommen|venir|venir|vir`),
  work:parse(`isim|öğretmen|teacher|Lehrer|professeur|profesor|professor\nisim|öğrenci|student|Schüler|élève|estudiante|estudante\nisim|kitap|book|Buch|livre|libro|livro\nisim|kalem|pen|Stift|stylo|bolígrafo|caneta\nfiil|okumak|read|lesen|lire|leer|ler\nfiil|yazmak|write|schreiben|écrire|escribir|escrever\nisim|sınıf|classroom|Klassenzimmer|salle de classe|aula|sala de aula`),
  nature:parse(`isim|güneş|sun|Sonne|soleil|sol|sol\nisim|kar|snow|Schnee|neige|nieve|neve\nisim|rüzgâr|wind|Wind|vent|viento|vento\nsıfat|sıcak|hot|heiß|chaud|caluroso|quente\nsıfat|soğuk|cold|kalt|froid|frío|frio\nisim|yaz|summer|Sommer|été|verano|verão\nisim|kış|winter|Winter|hiver|invierno|inverno`),
 },
 A2:{
  daily:parse(`isim|eczane|pharmacy|Apotheke|pharmacie|farmacia|farmácia\nisim|posta|post office|Post|bureau de poste|correos|correios\nisim|fatura|invoice|Rechnung|facture|factura|fatura\nfiil|değiştirmek|exchange|umtauschen|échanger|cambiar|trocar\nfiil|bozulmak|break down|kaputtgehen|tomber en panne|averiarse|avariar\nifade|sıra beklemek|wait in line|Schlange stehen|faire la queue|hacer cola|esperar na fila\nsıfat|müsait|available|verfügbar|disponible|disponible|disponível`),
  people:parse(`sıfat|utangaç|shy|schüchtern|timide|tímido|tímido\nsıfat|dürüst|honest|ehrlich|honnête|honesto|honesto\nsıfat|heyecanlı|excited|aufgeregt|enthousiaste|emocionado|entusiasmado\nfiil|kutlamak|celebrate|feiern|fêter|celebrar|celebrar\nfiil|tartışmak|argue|streiten|se disputer|discutir|discutir\nisim|hediye|gift|Geschenk|cadeau|regalo|presente\nisim|ilişki|relationship|Beziehung|relation|relación|relação`),
  food:parse(`isim|garson|waiter|Kellner|serveur|camarero|empregado de mesa\nisim|menü|menu|Speisekarte|menu|menú|ementa\nisim|indirim|discount|Rabatt|réduction|descuento|desconto\nfiil|ödemek|pay|bezahlen|payer|pagar|pagar\nfiil|denemek|try|probieren|goûter|probar|provar\nsıfat|taze|fresh|frisch|frais|fresco|fresco\nsıfat|vejetaryen|vegetarian|vegetarisch|végétarien|vegetariano|vegetariano`),
  travel:parse(`isim|resepsiyon|reception|Rezeption|réception|recepción|receção\nisim|tek kişilik oda|single room|Einzelzimmer|chambre simple|habitación individual|quarto individual\nisim|bagaj|luggage|Gepäck|bagages|equipaje|bagagem\nfiil|check-in yapmak|check in|einchecken|s’enregistrer|registrarse|fazer check-in\nfiil|kaçırmak|miss|verpassen|rater|perder|perder\nsıfat|dolu|fully booked|ausgebucht|complet|completo|esgotado\nisim|gezi|excursion|Ausflug|excursion|excursión|excursão`),
  work:parse(`isim|maaş|salary|Gehalt|salaire|salario|salário\nisim|mola|break|Pause|pause|descanso|pausa\nisim|özgeçmiş|CV|Lebenslauf|CV|currículum|currículo\nfiil|tamamlamak|complete|erledigen|terminer|completar|concluir\nfiil|açıklamak|explain|erklären|expliquer|explicar|explicar\nsıfat|yarı zamanlı|part-time|Teilzeit|à temps partiel|a tiempo parcial|a tempo parcial\nisim|müşteri|customer|Kunde|client|cliente|cliente`),
  nature:parse(`isim|çöp kutusu|bin|Mülleimer|poubelle|papelera|caixote do lixo\nisim|trafik|traffic|Verkehr|circulation|tráfico|trânsito\nisim|kavşak|crossroads|Kreuzung|carrefour|cruce|cruzamento\nfiil|ayırmak|sort|sortieren|trier|separar|separar\nfiil|kirletmek|pollute|verschmutzen|polluer|contaminar|poluir\nsıfat|sessiz|quiet|ruhig|calme|tranquilo|sossegado\nisim|bisiklet yolu|cycle lane|Radweg|piste cyclable|carril bici|ciclovia`),
 },
 B1:{
  daily:parse(`isim|öz güven|self-confidence|Selbstvertrauen|confiance en soi|autoconfianza|autoconfiança\nisim|başarı|achievement|Erfolg|réussite|logro|conquista\nfiil|uyum sağlamak|adjust|sich umstellen|s’adapter|adaptarse|adaptar-se\nfiil|vazgeçmek|give up|aufgeben|abandonner|rendirse|desistir\nsıfat|beklenmedik|unexpected|unerwartet|inattendu|inesperado|inesperado\nisim|fırsat|opportunity|Gelegenheit|occasion|oportunidad|oportunidade\nisim|zorluk|challenge|Herausforderung|défi|desafío|desafio`),
  people:parse(`isim|anlaşmazlık|disagreement|Meinungsverschiedenheit|désaccord|desacuerdo|desacordo\nisim|bakış açısı|point of view|Standpunkt|point de vue|punto de vista|ponto de vista\nfiil|desteklemek|support|unterstützen|soutenir|apoyar|apoiar\nfiil|eleştirmek|criticise|kritisieren|critiquer|criticar|criticar\nsıfat|düşünceli|thoughtful|rücksichtsvoll|attentionné|considerado|atencioso\nsıfat|bencil|selfish|egoistisch|égoïste|egoísta|egoísta\nisim|davranış|behaviour|Verhalten|comportement|comportamiento|comportamento`),
  food:parse(`isim|protein|protein|Eiweiß|protéine|proteína|proteína\nisim|lif|fibre|Ballaststoff|fibre|fibra|fibra\nsıfat|işlenmiş|processed|verarbeitet|transformé|procesado|processado\nfiil|kaçınmak|avoid|vermeiden|éviter|evitar|evitar\nfiil|tüketmek|consume|konsumieren|consommer|consumir|consumir\nisim|porsiyon|portion|Portion|portion|porción|porção\nisim|reçete|recipe|Rezept|recette|receta|receita`),
  travel:parse(`isim|iade|refund|Rückerstattung|remboursement|reembolso|reembolso\nisim|arızа|breakdown|Panne|panne|avería|avaria\nfiil|ertelemek|postpone|verschieben|reporter|posponer|adiar\nfiil|çözmek|resolve|lösen|résoudre|resolver|resolver\nsıfat|uygunsuz|inconvenient|unpraktisch|peu pratique|inconveniente|inconveniente\nisim|seyahat sigortası|travel insurance|Reiseversicherung|assurance voyage|seguro de viaje|seguro de viagem\nisim|alternatif|alternative|Alternative|alternative|alternativa|alternativa`),
  work:parse(`isim|staj|internship|Praktikum|stage|prácticas|estágio\nisim|mülakat|interview|Vorstellungsgespräch|entretien|entrevista|entrevista\nfiil|araştırmak|research|recherchieren|rechercher|investigar|pesquisar\nfiil|geliştirmek|improve|verbessern|améliorer|mejorar|melhorar\nsıfat|zorunlu|compulsory|verpflichtend|obligatoire|obligatorio|obrigatório\nisim|burs|scholarship|Stipendium|bourse|beca|bolsa de estudo\nisim|terfi|promotion|Beförderung|promotion|ascenso|promoção`),
  nature:parse(`isim|yenilenebilir enerji|renewable energy|erneuerbare Energie|énergie renouvelable|energía renovable|energia renovável\nisim|nesli tükenme|extinction|Aussterben|extinction|extinción|extinção\nfiil|tasarruf etmek|conserve|sparen|économiser|ahorrar|poupar\nfiil|zarar vermek|damage|schädigen|endommager|dañar|danificar\nsıfat|çevre dostu|eco-friendly|umweltfreundlich|écologique|ecológico|ecológico\nisim|habitat|habitat|Lebensraum|habitat|hábitat|habitat\nisim|kirlilik|pollution|Verschmutzung|pollution|contaminación|poluição`),
 },
 B2:{
  daily:parse(`isim|iş-yaşam dengesi|work-life balance|Work-Life-Balance|équilibre vie professionnelle-vie privée|conciliación laboral|equilíbrio trabalho-vida\nisim|esneklik|flexibility|Flexibilität|flexibilité|flexibilidad|flexibilidade\nfiil|ertelemek|procrastinate|aufschieben|procrastiner|procrastinar|procrastinar\nfiil|benimsemek|adopt|übernehmen|adopter|adoptar|adotar\nsıfat|verimli|efficient|effizient|efficace|eficiente|eficiente\nisim|tükenmişlik|burnout|Burnout|épuisement professionnel|agotamiento|esgotamento\nisim|refah|well-being|Wohlbefinden|bien-être|bienestar|bem-estar`),
  people:parse(`isim|kapsayıcılık|inclusion|Inklusion|inclusion|inclusión|inclusão\nisim|ayrımcılık|discrimination|Diskriminierung|discrimination|discriminación|discriminação\nfiil|güçlendirmek|empower|befähigen|autonomiser|empoderar|capacitar\nfiil|kalıplaştırmak|stereotype|stereotypisieren|stéréotyper|estereotipar|estereotipar\nsıfat|çeşitli|diverse|vielfältig|divers|diverso|diverso\nisim|toplumsal norm|social norm|soziale Norm|norme sociale|norma social|norma social\nisim|eşitlik|equality|Gleichheit|égalité|igualdad|igualdade`),
  food:parse(`isim|organik tarım|organic farming|ökologische Landwirtschaft|agriculture biologique|agricultura ecológica|agricultura biológica\nisim|gıda israfı|food waste|Lebensmittelverschwendung|gaspillage alimentaire|desperdicio alimentario|desperdício alimentar\nfiil|kaynak sağlamak|source|beschaffen|s’approvisionner|abastecerse|abastecer\nfiil|etiketlemek|label|kennzeichnen|étiqueter|etiquetar|rotular\nsıfat|yerel|locally sourced|regional|local|de proximidad|local\nisim|üretici|producer|Erzeuger|producteur|productor|produtor\nisim|ambalaj|packaging|Verpackung|emballage|envase|embalagem`),
  travel:parse(`isim|özgünlük|authenticity|Authentizität|authenticité|autenticidad|autenticidade\nisim|kültürel miras|cultural heritage|Kulturerbe|patrimoine culturel|patrimonio cultural|património cultural\nfiil|korumak|conserve|erhalten|conserver|conservar|conservar\nfiil|ticarileştirmek|commercialise|vermarkten|commercialiser|comercializar|comercializar\nsıfat|erişilebilir|accessible|barrierefrei|accessible|accesible|acessível\nisim|yerel halk|local community|lokale Bevölkerung|communauté locale|comunidad local|comunidade local\nisim|aşırı turizm|overtourism|Übertourismus|surtourisme|sobreturismo|turismo excessivo`),
  work:parse(`isim|paydaş|stakeholder|Interessengruppe|partie prenante|parte interesada|parte interessada\nisim|gündem|agenda|Tagesordnung|ordre du jour|orden del día|ordem de trabalhos\nfiil|devretmek|delegate|delegieren|déléguer|delegar|delegar\nfiil|uzlaştırmak|reconcile|vereinbaren|concilier|conciliar|conciliar\nsıfat|uygulanabilir|feasible|machbar|réalisable|viable|viável\nisim|verimlilik|productivity|Produktivität|productivité|productividad|produtividade\nisim|anlaşmazlık çözümü|conflict resolution|Konfliktlösung|résolution de conflit|resolución de conflictos|resolução de conflitos`),
  nature:parse(`isim|sera gazı|greenhouse gas|Treibhausgas|gaz à effet de serre|gas de efecto invernadero|gás com efeito de estufa\nisim|toplu taşıma|public transport|öffentlicher Verkehr|transports en commun|transporte público|transporte público\nfiil|dengelemek|offset|ausgleichen|compenser|compensar|compensar\nfiil|dönüştürmek|transform|umgestalten|transformer|transformar|transformar\nsıfat|düşük karbonlu|low-carbon|kohlenstoffarm|bas carbone|bajo en carbono|de baixo carbono\nisim|yoğunluk|density|Dichte|densité|densidad|densidade\nisim|altyapı|infrastructure|Infrastruktur|infrastructure|infraestructura|infraestrutura`),
 },
 C1:{
  daily:parse(`isim|gözetim|surveillance|Überwachung|surveillance|vigilancia|vigilância\nisim|bakım emeği|care work|Sorgearbeit|travail du care|trabajo de cuidados|trabalho de cuidado\nfiil|normalleştirmek|normalise|normalisieren|normaliser|normalizar|normalizar\nfiil|müzakere etmek|negotiate|aushandeln|négocier|negociar|negociar\nsıfat|geçirgen|porous|durchlässig|poreux|poroso|poroso\nisim|özerklik|autonomy|Autonomie|autonomie|autonomía|autonomia\nisim|gündelik pratik|everyday practice|Alltagspraxis|pratique quotidienne|práctica cotidiana|prática quotidiana`),
  people:parse(`isim|bilişsel çelişki|cognitive dissonance|kognitive Dissonanz|dissonance cognitive|disonancia cognitiva|dissonância cognitiva\nisim|duygusal emek|emotional labour|Emotionsarbeit|travail émotionnel|trabajo emocional|trabalho emocional\nfiil|damgalamak|stigmatise|stigmatisieren|stigmatiser|estigmatizar|estigmatizar\nfiil|özdeşleşmek|identify with|sich identifizieren|s’identifier|identificarse|identificar-se\nsıfat|içgüdüsel|instinctive|instinktiv|instinctif|instintivo|instintivo\nisim|dayanıklılık|resilience|Resilienz|résilience|resiliencia|resiliência\nisim|benlik algısı|self-image|Selbstbild|image de soi|autoimagen|autoimagem`),
  food:parse(`isim|gıda güvencesi|food security|Ernährungssicherheit|sécurité alimentaire|seguridad alimentaria|segurança alimentar\nisim|tarım politikası|agricultural policy|Agrarpolitik|politique agricole|política agraria|política agrícola\nfiil|düzenlemek|regulate|regulieren|réglementer|regular|regular\nfiil|sübvanse etmek|subsidise|subventionieren|subventionner|subvencionar|subsidiar\nsıfat|adil|equitable|gerecht|équitable|equitativo|equitativo\nisim|tedarik kırılganlığı|supply vulnerability|Versorgungsrisiko|vulnérabilité d’approvisionnement|vulnerabilidad de suministro|vulnerabilidade do abastecimento\nisim|geçim kaynağı|livelihood|Lebensgrundlage|moyen de subsistance|medio de vida|meio de subsistência`),
  travel:parse(`isim|zorunlu göç|forced migration|Zwangsmigration|migration forcée|migración forzada|migração forçada\nisim|entegrasyon politikası|integration policy|Integrationspolitik|politique d’intégration|política de integración|política de integração\nfiil|kök salmak|put down roots|Wurzeln schlagen|s’enraciner|echar raíces|criar raízes\nfiil|ötekileştirmek|other|ausgrenzen|altériser|otredad|alterizar\nsıfat|vatansız|stateless|staatenlos|apatride|apátrida|apátrida\nisim|ev sahibi toplum|host society|Aufnahmegesellschaft|société d’accueil|sociedad de acogida|sociedade de acolhimento\nisim|kültürlerarasılık|interculturality|Interkulturalität|interculturalité|interculturalidad|interculturalidade`),
  work:parse(`isim|metodoloji|methodology|Methodik|méthodologie|metodología|metodologia\nisim|hesap verebilirlik|accountability|Rechenschaftspflicht|redevabilité|rendición de cuentas|prestação de contas\nfiil|çerçevelemek|frame|rahmen|cadrer|enmarcar|enquadrar\nfiil|sentezlemek|synthesise|synthetisieren|synthétiser|sintetizar|sintetizar\nsıfat|ampirik|empirical|empirisch|empirique|empírico|empírico\nisim|çıkar çatışması|conflict of interest|Interessenkonflikt|conflit d’intérêts|conflicto de intereses|conflito de interesses\nisim|araştırma etiği|research ethics|Forschungsethik|éthique de la recherche|ética de investigación|ética de investigação`),
  nature:parse(`isim|ekosistem hizmeti|ecosystem service|Ökosystemleistung|service écosystémique|servicio ecosistémico|serviço ecossistémico\nisim|döngüsel ekonomi|circular economy|Kreislaufwirtschaft|économie circulaire|economía circular|economia circular\nfiil|uyarlamak|adapt|anpassen|adapter|adaptar|adaptar\nfiil|onarmak|restore|wiederherstellen|restaurer|restaurar|restaurar\nsıfat|yenileyici|regenerative|regenerativ|régénératif|regenerativo|regenerativo\nisim|eşik noktası|tipping point|Kipppunkt|point de bascule|punto de inflexión|ponto de rutura\nisim|doğa temelli çözüm|nature-based solution|naturbasierte Lösung|solution fondée sur la nature|solución basada en la naturaleza|solução baseada na natureza`),
 },
 C2:{
  daily:parse(`isim|yaşam dünyası|lifeworld|Lebenswelt|monde vécu|mundo de la vida|mundo da vida\nisim|ritüelleşme|ritualisation|Ritualisierung|ritualisation|ritualización|ritualização\nfiil|yadırgatmak|defamiliarise|verfremden|défamiliariser|desfamiliarizar|desfamiliarizar\nfiil|yeniden anlamlandırmak|re-signify|umdeuten|resignifier|resignificar|ressignificar\nsıfat|örtük|implicit|implizit|implicite|implícito|implícito\nisim|zamansallık|temporality|Temporalität|temporalité|temporalidad|temporalidade\nisim|maddi kültür|material culture|materielle Kultur|culture matérielle|cultura material|cultura material`),
  people:parse(`isim|failiyet|agency|Handlungsmacht|agentivité|agencia|agência\nisim|tanıma siyaseti|politics of recognition|Anerkennungspolitik|politique de reconnaissance|política de reconocimiento|política de reconhecimento\nfiil|araçsallaştırmak|instrumentalise|instrumentalisieren|instrumentaliser|instrumentalizar|instrumentalizar\nfiil|meşrulaştırmak|legitimise|legitimieren|légitimer|legitimar|legitimar\nsıfat|normatif|normative|normativ|normatif|normativo|normativo\nisim|ötekilik|otherness|Andersheit|altérité|alteridad|alteridade\nisim|etik ikilem|ethical dilemma|ethisches Dilemma|dilemme éthique|dilema ético|dilema ético`),
  food:parse(`isim|gıda rejimi|food regime|Ernährungsregime|régime alimentaire|régimen alimentario|regime alimentar\nisim|ekolojik borç|ecological debt|ökologische Schuld|dette écologique|deuda ecológica|dívida ecológica\nfiil|sömürüsüzleştirmek|decolonise|dekolonisieren|décoloniser|descolonizar|descolonizar\nfiil|yeniden dağıtmak|redistribute|umverteilen|redistribuer|redistribuir|redistribuir\nsıfat|çıkarımsal|extractive|extraktiv|extractiviste|extractivo|extrativista\nisim|müşterekler|commons|Gemeingüter|communs|bienes comunes|bens comuns\nisim|beslenme adaleti|food justice|Ernährungsgerechtigkeit|justice alimentaire|justicia alimentaria|justiça alimentar`),
  travel:parse(`isim|hareketlilik rejimi|mobility regime|Mobilitätsregime|régime de mobilité|régimen de movilidad|regime de mobilidade\nisim|diasporik bilinç|diasporic consciousness|diasporisches Bewusstsein|conscience diasporique|conciencia diaspórica|consciência diaspórica\nfiil|sınırlandırmak|border|begrenzen|frontiériser|fronterizar|fronteirizar\nfiil|yeniden yerelleştirmek|reterritorialise|reterritorialisieren|reterritorialiser|reterritorializar|reterritorializar\nsıfat|ulusaşırı|transnational|transnational|transnational|transnacional|transnacional\nisim|geçiş alanı|liminal space|Schwellenraum|espace liminal|espacio liminal|espaço liminar\nisim|hareket hakkı|right to mobility|Recht auf Mobilität|droit à la mobilité|derecho a la movilidad|direito à mobilidade`),
  work:parse(`isim|bilgi siyaseti|politics of knowledge|Wissenspolitik|politique du savoir|política del conocimiento|política do conhecimento\nisim|paradigma|paradigm|Paradigma|paradigme|paradigma|paradigma\nfiil|doğallaştırmak|naturalise|naturalisieren|naturaliser|naturalizar|naturalizar\nfiil|yapısöküme uğratmak|deconstruct|dekonstruieren|déconstruire|deconstruir|desconstruir\nsıfat|hegemonik|hegemonic|hegemonial|hégémonique|hegemónico|hegemónico\nisim|söylemsel oluşum|discursive formation|diskursive Formation|formation discursive|formación discursiva|formação discursiva\nisim|epistemik adaletsizlik|epistemic injustice|epistemische Ungerechtigkeit|injustice épistémique|injusticia epistémica|injustiça epistémica`),
  nature:parse(`isim|doğa-kültür ikiliği|nature-culture divide|Natur-Kultur-Dualismus|dualisme nature-culture|dualismo naturaleza-cultura|dualismo natureza-cultura\nisim|çok türlü adalet|multispecies justice|Multispezies-Gerechtigkeit|justice multiespèces|justicia multiespecie|justiça multiespécies\nfiil|insandışılaştırmak|dehumanise|entmenschlichen|déshumaniser|deshumanizar|desumanizar\nfiil|yeniden düşünmek|reconceptualise|neu konzeptualisieren|reconceptualiser|reconceptualizar|reconceptualizar\nsıfat|ilişkisel|relational|relational|relationnel|relacional|relacional\nisim|derin ekoloji|deep ecology|Tiefenökologie|écologie profonde|ecología profunda|ecologia profunda\nisim|ekolojik yas|ecological grief|ökologische Trauer|deuil écologique|duelo ecológico|luto ecológico`),
 }
};

const skills: Record<CategoryId, ExamSkill> = {daily:"dinleme",people:"konuşma",food:"dinleme",travel:"okuma",work:"yazma",nature:"okuma"};
const prompts: Record<ExamSkill,string> = {okuma:"Metinde eş anlamlı veya karşıt bağlamı bul.",dinleme:"Sözcüğü doğal hızda dinle ve ana fikri yakala.",yazma:"Sözcüğü gerekçeli bir cümlede kullan.",konuşma:"Sözcükle görüşünü açıklayıp bir örnek ver."};

export function buildDeck(language:LanguageId, level:Level, category:CategoryId): WordCard[] {
 const categoryLabel=getCategories(level).find(x=>x.id===category)!.label;
 return [...bank[level][category],...extra[level][category]].map((seed,index)=>({id:`${language}-${level}-${category}-${index}`,language,level,category,categoryLabel,index,term:seed[language],lemma:seed[language],turkish:seed.tr,partOfSpeech:seed.pos,exam:EXAM_PROFILES[language][level],skill:skills[category],example:prompts[skills[category]],exampleTr:`Aktif görev: ${seed.tr} sözcüğünü ezberden üret.`,reviewStatus:"editoryal çekirdek"}));
}

const textFrames: Record<LanguageId, [string,string,string]> = {
 en:["This study dossier explores", "Read the vocabulary aloud, notice how every item changes the meaning of its sentence, and then cover the list. Reconstruct the ideas from memory before checking the original wording.", "In an exam, identify the topic, infer meaning from context, and reuse the vocabulary in a precise answer. Compare related ideas, justify an opinion, and finish with a concrete example."],
 de:["Dieses Lerndossier untersucht", "Lies den Wortschatz laut, achte darauf, wie jeder Ausdruck die Aussage verändert, und decke dann die Liste ab. Rekonstruiere die Gedanken aus dem Gedächtnis.", "In der Prüfung bestimmst du das Thema, erschließt Bedeutungen aus dem Kontext und verwendest den Wortschatz in einer präzisen Antwort. Begründe deine Meinung mit einem konkreten Beispiel."],
 fr:["Ce dossier d’étude explore", "Lis le vocabulaire à voix haute, observe comment chaque expression modifie le sens, puis cache la liste. Reconstruis les idées de mémoire avant de vérifier le texte.", "À l’examen, repère le thème, déduis le sens grâce au contexte et réutilise le vocabulaire dans une réponse précise. Justifie ton opinion par un exemple concret."],
 es:["Este dossier de estudio explora", "Lee el vocabulario en voz alta, observa cómo cada expresión cambia el sentido y después tapa la lista. Reconstruye las ideas de memoria antes de comprobar el texto.", "En el examen, identifica el tema, deduce significados por el contexto y reutiliza el vocabulario en una respuesta precisa. Justifica tu opinión con un ejemplo concreto."],
 pt:["Este dossiê de estudo explora", "Lê o vocabulário em voz alta, observa como cada expressão altera o sentido e depois tapa a lista. Reconstrói as ideias de memória antes de verificares o texto.", "No exame, identifica o tema, deduz significados pelo contexto e reutiliza o vocabulário numa resposta precisa. Justifica a tua opinião com um exemplo concreto."],
};
const reflectionFrames: Record<LanguageId,string[]> = {
 en:["First, group the terms by meaning and explain the link between them without translating word for word.","Next, imagine a realistic situation in which at least three of the expressions are necessary and say the response aloud.","Finally, write a short conclusion that contrasts two ideas, uses evidence, and preserves the appropriate register."],
 de:["Ordne zuerst die Begriffe nach ihrer Bedeutung und erkläre ihren Zusammenhang, ohne Wort für Wort zu übersetzen.","Stell dir danach eine realistische Situation vor, in der mindestens drei Ausdrücke nötig sind, und sprich deine Antwort laut aus.","Schreibe zum Schluss eine kurze Folgerung, die zwei Gedanken gegenüberstellt, Belege nutzt und das passende Register wahrt."],
 fr:["Regroupe d’abord les termes selon leur sens et explique leur lien sans traduire mot à mot.","Imagine ensuite une situation réaliste où au moins trois expressions sont nécessaires et formule la réponse à voix haute.","Rédige enfin une brève conclusion qui oppose deux idées, s’appuie sur une preuve et respecte le registre attendu."],
 es:["Agrupa primero los términos por significado y explica su relación sin traducir palabra por palabra.","Después imagina una situación realista en la que necesites al menos tres expresiones y formula la respuesta en voz alta.","Por último, redacta una conclusión breve que contraste dos ideas, aporte pruebas y mantenga el registro adecuado."],
 pt:["Agrupa primeiro os termos por significado e explica a relação entre eles sem traduzir palavra por palavra.","Depois imagina uma situação realista em que precises de pelo menos três expressões e formula a resposta em voz alta.","Por fim, escreve uma conclusão breve que contraste duas ideias, apresente provas e mantenha o registo adequado."],
};

export function buildStudyText(language:LanguageId, level:Level, category:CategoryId){
 const deck=buildDeck(language,level,category), terms=deck.map(card=>card.term).join(", "), [lead,recall,exam]=textFrames[language];
 const opening=`${lead} ${getCategories(level).find(item=>item.id===category)!.label.toLocaleLowerCase("tr-TR")}: ${terms}.`;
 const paragraph=`${recall} ${exam}`;
 let text=`${opening}\n\n${paragraph}`, step=0;
 while(text.length<1000){text+=`\n\n${reflectionFrames[language][step%reflectionFrames[language].length]}`;step++;}
 return text;
}

export function normalizeAnswer(value:string){return value.trim().toLocaleLowerCase("tr-TR").normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[.,!?;:'’\-"]/g,"").replace(/\s+/g," ");}
export function validateCurriculum(){return auditCurriculum().length===0;}
export function auditCurriculum(){
 const errors:string[]=[]; const signatures=new Set<string>(); let total=0;
 for(const level of LEVELS){const labels=getCategories(level).map(x=>x.label);const signature=labels.join("|");if(labels.length!==6||new Set(labels).size!==6)errors.push(`${level}: kategori seti eksik/tekrarlı`);if(signatures.has(signature))errors.push(`${level}: kategori seti başka seviyenin kopyası`);signatures.add(signature);}
 for(const {id:language} of LANGUAGES)for(const {id:category} of CATEGORIES){const seen=new Set<string>();for(const level of LEVELS){const deck=buildDeck(language,level,category);total+=deck.length;if(deck.length!==10)errors.push(`${language}/${level}/${category}: 10 lemma yerine ${deck.length}`);const text=buildStudyText(language,level,category);if(text.length<1000)errors.push(`${language}/${level}/${category}: çalışma metni 1000 karakterden kısa`);for(const card of deck){const lemma=normalizeAnswer(card.lemma);if(seen.has(lemma))errors.push(`${language}/${category}: seviyeler arası tekrar: ${lemma}`);seen.add(lemma);if(!text.includes(card.term))errors.push(`${card.id}: çalışma metninde yok`);if(!card.partOfSpeech||!card.exam||!card.skill)errors.push(`${card.id}: metadata eksik`);if(/nuanced use|critical reading|nuancierter gebrauch/i.test(card.term))errors.push(`${card.id}: yapay türetim`);}}}
 if(total!==1800)errors.push(`toplam kart sayısı 1800 yerine ${total}`);
 return errors;
}
