"use client";
import Link from "next/link";
import { FormEvent, useMemo, useState } from "react";
import { useParams, useSearchParams } from "next/navigation";
import { SiteNav } from "../SiteNav";
import { DeckControls } from "../DeckControls";
import { SpeakButton } from "../SpeakButton";
import { LANGUAGES, LEVELS, buildDeck, buildStudyText, getCategories, normalizeAnswer, type CategoryId, type LanguageId, type Level } from "../../lib/curriculum";
import { PRACTICE_METHODS, isPracticeMode } from "../../lib/practice";
type Feedback="idle"|"correct"|"wrong";

export default function MethodRoom(){
 const params=useParams<{mode:string}>(),search=useSearchParams(),routeMode=params.mode,isValid=isPracticeMode(routeMode),method=PRACTICE_METHODS.find(item=>item.id===routeMode);
 const queryLanguage=search.get("lang") as LanguageId,queryLevel=search.get("level") as Level,queryCategory=search.get("category") as CategoryId;
 const[language,setLanguage]=useState<LanguageId>(LANGUAGES.some(item=>item.id===queryLanguage)?queryLanguage:"en"),[level,setLevel]=useState<Level>(LEVELS.includes(queryLevel)?queryLevel:"A1"),[category,setCategory]=useState<CategoryId>(getCategories(LEVELS.includes(queryLevel)?queryLevel:"A1").some(item=>item.id===queryCategory)?queryCategory:"daily"),[index,setIndex]=useState(0),[revealed,setRevealed]=useState(false),[answer,setAnswer]=useState(""),[feedback,setFeedback]=useState<Feedback>("idle");
 const categories=getCategories(level),deck=useMemo(()=>buildDeck(language,level,category),[language,level,category]),card=deck[index%deck.length],pool=useMemo(()=>categories.flatMap(item=>buildDeck(language,level,item.id)),[language,level,categories]),alternatives=useMemo(()=>pool.filter(item=>item.id!==card.id&&normalizeAnswer(item.turkish)!==normalizeAnswer(card.turkish)),[pool,card]);
 const choices=useMemo(()=>{const offset=(index*7)%alternatives.length;return [card,...[0,1,2].map(step=>alternatives[(offset+step*5)%alternatives.length])].sort((a,b)=>a.turkish.localeCompare(b.turkish,"tr"))},[card,alternatives,index]);
 const categoryChoices=useMemo(()=>{const correct=categories.find(item=>item.id===card.category)!,others=categories.filter(item=>item.id!==card.category),offset=index%others.length;return [correct,...[0,1,2].map(step=>others[(offset+step)%others.length])].sort((a,b)=>a.label.localeCompare(b.label,"tr"))},[categories,card.category,index]),studyText=useMemo(()=>buildStudyText(language,level,category),[language,level,category]),sentenceValid=answer.trim().split(/\s+/).length>=5&&normalizeAnswer(answer).includes(normalizeAnswer(card.term));
 function reset(){setRevealed(false);setAnswer("");setFeedback("idle")};function next(){setIndex(value=>(value+1)%deck.length);reset()};function changeLevel(value:Level){setLevel(value);setCategory(getCategories(value)[0].id);setIndex(0);reset()};function changeCategory(value:CategoryId){setCategory(value);setIndex(0);reset()};function changeLanguage(value:LanguageId){setLanguage(value);setIndex(0);reset()};function check(event:FormEvent){event.preventDefault();setFeedback(normalizeAnswer(answer)===normalizeAnswer(card.term)?"correct":"wrong");setRevealed(true)}
 if(!isValid||!method)return <main><SiteNav/><section className="invalid-room"><span>404 / YÖNTEM YOK</span><h1>Bu çalışma odası bulunamadı.</h1><Link href="/practice">YÖNTEMLERE DÖN →</Link></section></main>;
 return <main><SiteNav/><section className={`method-room room-${method.accent} ${feedback}`}><header className="room-head"><Link href="/practice">← YÖNTEMLER</Link><div><span className="eyebrow">{method.number} / {method.meta}</span><h1>{method.title}</h1><p>{method.description}</p></div><aside><span>TAHMİNİ SÜRE</span><b>{method.duration}</b></aside></header><div className="room-controls"><DeckControls language={language} level={level} category={category} onLanguage={changeLanguage} onLevel={changeLevel} onCategory={changeCategory}/></div><section className="room-workspace" aria-live="polite"><header><div><span>{level} · {card.categoryLabel}</span><b>{card.exam}</b></div><div className="room-progress"><strong>{String(index+1).padStart(2,"0")}</strong><span>/ {deck.length}</span><i><small style={{width:`${(index+1)/deck.length*100}%`}}/></i></div></header><div className="room-body">
 {routeMode==="flash"&&<div className="room-flash"><button onClick={()=>setRevealed(value=>!value)}><span>{revealed?"TÜRKÇE":"HEDEF DİL"}</span><strong>{revealed?card.turkish:card.term}</strong><small>{revealed?card.partOfSpeech:"CEVABI AÇ ↗"}</small></button>{revealed&&<button className="room-next" onClick={next}>SONRAKİ KART →</button>}</div>}
 {routeMode==="choice"&&<ChoiceExercise card={card} choices={choices} revealed={revealed} feedback={feedback} onChoose={correct=>{setFeedback(correct?"correct":"wrong");setRevealed(true)}} onNext={next}/>}
 {routeMode==="free"&&<RecallExercise prompt={card.turkish} answer={answer} revealed={revealed} feedback={feedback} expected={card.term} onAnswer={value=>{setAnswer(value);setRevealed(false);setFeedback("idle")}} onSubmit={check} onNext={next}/>}
 {routeMode==="listen"&&<form className="room-form room-listen" onSubmit={check}><span>EKRANA BAKMADAN DİNLE</span><SpeakButton card={card} label="▶ SESİ OYNAT"/><input aria-label="Duyduğun kelime" value={answer} onChange={event=>{setAnswer(event.target.value);setRevealed(false);setFeedback("idle")}} placeholder="Duyduğunu yaz…" autoFocus/><p>{revealed?(feedback==="correct"?"Doğru duydun.":`Doğru yazım: ${card.term}`):"Sesi gerektiği kadar tekrarla; sonra cevabı tek seferde kontrol et."}</p><div><button>KONTROL ET</button>{revealed&&<button type="button" onClick={next}>SONRAKİ →</button>}</div></form>}
 {routeMode==="sentence"&&<form className="room-form" onSubmit={event=>{event.preventDefault();if(sentenceValid)setRevealed(true)}}><span>BAĞLAMLI ÜRETİM</span><h2>{card.term} <small>· {card.turkish}</small></h2><textarea value={answer} onChange={event=>{setAnswer(event.target.value);setRevealed(false)}} placeholder={`“${card.term}” ile en az 5 kelimelik bir cümle…`} autoFocus/><p>{sentenceValid?"Hazır: anlam, dilbilgisi ve register kontrolünü yap.":`“${card.term}” ifadesi ve en az 5 kelime gerekli.`}</p><div><button disabled={!sentenceValid}>CÜMLEYİ DENETLE</button>{revealed&&<button type="button" onClick={next}>SONRAKİ →</button>}</div></form>}
 {routeMode==="category"&&<div className="room-choice"><div className="room-prompt"><span>SEMANTİK AĞ</span><h2>{card.term}</h2><p>{card.turkish} hangi konu alanına ait?</p></div><div className="room-options">{categoryChoices.map(option=><button disabled={revealed} className={revealed&&option.id===card.category?"right":""} key={option.id} onClick={()=>{setFeedback(option.id===card.category?"correct":"wrong");setRevealed(true)}}>{option.icon}<b>{option.label}</b></button>)}{revealed&&<button className="room-next" onClick={next}>SONRAKİ →</button>}</div></div>}
 {routeMode==="text"&&<div className="room-reading"><header><div><span>TÜM {deck.length} KELİME · {studyText.length} KARAKTER</span><h2>{card.categoryLabel}</h2></div><SpeakButton card={{...card,term:studyText}} label="METNİ DİNLE"/></header><p>{studyText}</p></div>}
 </div></section></section></main>
}

function ChoiceExercise({card,choices,revealed,feedback,onChoose,onNext}:{card:ReturnType<typeof buildDeck>[number];choices:ReturnType<typeof buildDeck>;revealed:boolean;feedback:Feedback;onChoose:(correct:boolean)=>void;onNext:()=>void}){return <div className="room-choice"><div className="room-prompt"><SpeakButton card={card} label="DİNLE"/><h2>{card.term}</h2><p>Doğru Türkçe karşılığı seç.</p></div><div className="room-options">{choices.map(choice=><button disabled={revealed} className={revealed&&choice.id===card.id?"right":""} key={choice.id} onClick={()=>onChoose(choice.id===card.id)}>{choice.turkish}</button>)}{revealed&&<button className="room-next" onClick={onNext}>{feedback==="correct"?"DOĞRU":"CEVABI İNCELE"} · SONRAKİ →</button>}</div></div>}
function RecallExercise({prompt,answer,revealed,feedback,expected,onAnswer,onSubmit,onNext}:{prompt:string;answer:string;revealed:boolean;feedback:Feedback;expected:string;onAnswer:(value:string)=>void;onSubmit:(event:FormEvent)=>void;onNext:()=>void}){return <form className="room-form" onSubmit={onSubmit}><span>TÜRKÇEDEN HEDEF DİLE</span><h2>{prompt}</h2><input aria-label="Cevap" value={answer} onChange={event=>onAnswer(event.target.value)} placeholder="Cevabını yaz…" autoComplete="off" autoFocus/><p>{revealed?(feedback==="correct"?"Doğru. Aktif hatırlama tamamlandı.":`Beklenen cevap: ${expected}`):"Enter ile kontrol et; aksan farkları normalize edilir."}</p><div><button>KONTROL ET</button>{revealed&&<button type="button" onClick={onNext}>SONRAKİ →</button>}</div></form>}
